import { defineConfig } from 'orval';

/**
 * Orval config for the SVAP frontend SDK.
 *
 * - Input: backend OpenAPI document (configurable via OPENAPI_URL).
 * - Output: `svm-fe/src/sdk/`, one folder per OpenAPI tag (FR-008 tree-shake friendly).
 * - Mode: TanStack Query option-factories matching the project's xCreateMutation /
 *   xRetrieveOptions naming convention (research.md D-002).
 * - Mutator: every generated call routes through `src/api/sdk-mutator.ts`, which
 *   delegates to the hand-written `src/api/client.ts` fetcher — that's where cookies,
 *   CSRF, and error-envelope handling actually live (research.md D-003 / FR-010 /
 *   FR-011 / FR-012). The mutator lives OUTSIDE `src/sdk/` because Orval's `clean`
 *   glob does not reliably honor negations; placing it inside would risk deletion
 *   on each regen.
 * - `clean` removes all stale generated files between runs.
 * - `header` callback puts a regen banner at the top of every generated file (FR-009).
 *
 * See `specs/004-frontend-orval-sdk/contracts/sdk-gen-command.md` for the full
 * contract this config implements.
 */
export default defineConfig({
  svap: {
    input: {
      target: process.env.OPENAPI_URL ?? 'http://localhost:8000/api/v1/openapi.json',
    },
    output: {
      mode: 'tags',
      target: 'src/sdk',
      schemas: 'src/sdk/schemas',
      client: 'react-query',
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: './src/api/sdk-mutator.ts',
          name: 'mutator',
        },
        header: () => [
          'Generated by orval — do not edit.',
          'Regenerate via: bun run sdk:gen',
        ],
      },
    },
  },
});
