/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivityLogDetail,
  ActivityLogList,
  AdminListActivityLogParams,
  HTTPValidationError
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType } from '../api/sdk-mutator';





export type adminListActivityLogResponse200 = {
  data: ActivityLogList
  status: 200
}

export type adminListActivityLogResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListActivityLogResponseSuccess = (adminListActivityLogResponse200) & {
  headers: Headers;
};
export type adminListActivityLogResponseError = (adminListActivityLogResponse422) & {
  headers: Headers;
};

export type adminListActivityLogResponse = (adminListActivityLogResponseSuccess | adminListActivityLogResponseError)

export const getAdminListActivityLogUrl = (params?: AdminListActivityLogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/activity-log?${stringifiedParams}` : `/api/v1/admin/activity-log`
}

/**
 * @summary List Activity Log
 */
export const adminListActivityLog = async (params?: AdminListActivityLogParams, options?: RequestInit): Promise<adminListActivityLogResponse> => {

  return mutator<adminListActivityLogResponse>(getAdminListActivityLogUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListActivityLogQueryKey = (params?: AdminListActivityLogParams,) => {
    return [
    `/api/v1/admin/activity-log`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListActivityLogQueryOptions = <TData = Awaited<ReturnType<typeof adminListActivityLog>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListActivityLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListActivityLog>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListActivityLogQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListActivityLog>>> = ({ signal }) => adminListActivityLog(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListActivityLog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListActivityLogQueryResult = NonNullable<Awaited<ReturnType<typeof adminListActivityLog>>>
export type AdminListActivityLogQueryError = ErrorType<HTTPValidationError>


export function useAdminListActivityLog<TData = Awaited<ReturnType<typeof adminListActivityLog>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListActivityLogParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListActivityLog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListActivityLog>>,
          TError,
          Awaited<ReturnType<typeof adminListActivityLog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListActivityLog<TData = Awaited<ReturnType<typeof adminListActivityLog>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListActivityLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListActivityLog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListActivityLog>>,
          TError,
          Awaited<ReturnType<typeof adminListActivityLog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListActivityLog<TData = Awaited<ReturnType<typeof adminListActivityLog>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListActivityLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListActivityLog>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Activity Log
 */

export function useAdminListActivityLog<TData = Awaited<ReturnType<typeof adminListActivityLog>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListActivityLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListActivityLog>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListActivityLogQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminGetActivityLogEntryResponse200 = {
  data: ActivityLogDetail
  status: 200
}

export type adminGetActivityLogEntryResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetActivityLogEntryResponseSuccess = (adminGetActivityLogEntryResponse200) & {
  headers: Headers;
};
export type adminGetActivityLogEntryResponseError = (adminGetActivityLogEntryResponse422) & {
  headers: Headers;
};

export type adminGetActivityLogEntryResponse = (adminGetActivityLogEntryResponseSuccess | adminGetActivityLogEntryResponseError)

export const getAdminGetActivityLogEntryUrl = (entryId: number,) => {




  return `/api/v1/admin/activity-log/${entryId}`
}

/**
 * @summary Get Activity Log Entry
 */
export const adminGetActivityLogEntry = async (entryId: number, options?: RequestInit): Promise<adminGetActivityLogEntryResponse> => {

  return mutator<adminGetActivityLogEntryResponse>(getAdminGetActivityLogEntryUrl(entryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetActivityLogEntryQueryKey = (entryId: number,) => {
    return [
    `/api/v1/admin/activity-log/${entryId}`
    ] as const;
    }


export const getAdminGetActivityLogEntryQueryOptions = <TData = Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError = ErrorType<HTTPValidationError>>(entryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetActivityLogEntryQueryKey(entryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetActivityLogEntry>>> = ({ signal }) => adminGetActivityLogEntry(entryId, { signal });





   return  { queryKey, queryFn, enabled: entryId !== null && entryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetActivityLogEntryQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetActivityLogEntry>>>
export type AdminGetActivityLogEntryQueryError = ErrorType<HTTPValidationError>


export function useAdminGetActivityLogEntry<TData = Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError = ErrorType<HTTPValidationError>>(
 entryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogEntry>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogEntry>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetActivityLogEntry<TData = Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError = ErrorType<HTTPValidationError>>(
 entryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogEntry>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogEntry>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetActivityLogEntry<TData = Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError = ErrorType<HTTPValidationError>>(
 entryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Activity Log Entry
 */

export function useAdminGetActivityLogEntry<TData = Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError = ErrorType<HTTPValidationError>>(
 entryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogEntry>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetActivityLogEntryQueryOptions(entryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






