/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  InviteUserRequest,
  InviteUserResponse
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminInviteUserResponse201 = {
  data: InviteUserResponse
  status: 201
}

export type adminInviteUserResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminInviteUserResponseSuccess = (adminInviteUserResponse201) & {
  headers: Headers;
};
export type adminInviteUserResponseError = (adminInviteUserResponse422) & {
  headers: Headers;
};

export type adminInviteUserResponse = (adminInviteUserResponseSuccess | adminInviteUserResponseError)

export const getAdminInviteUserUrl = () => {




  return `/api/v1/admin/users/invite`
}

/**
 * @summary Invite User
 */
export const adminInviteUser = async (inviteUserRequest: InviteUserRequest, options?: RequestInit): Promise<adminInviteUserResponse> => {

  return mutator<adminInviteUserResponse>(getAdminInviteUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(inviteUserRequest)
  }
);}




export const getAdminInviteUserMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminInviteUser>>, TError,{data: BodyType<InviteUserRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminInviteUser>>, TError,{data: BodyType<InviteUserRequest>}, TContext> => {

const mutationKey = ['adminInviteUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminInviteUser>>, {data: BodyType<InviteUserRequest>}> = (props) => {
          const {data} = props ?? {};

          return  adminInviteUser(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminInviteUserMutationResult = NonNullable<Awaited<ReturnType<typeof adminInviteUser>>>
    export type AdminInviteUserMutationBody = BodyType<InviteUserRequest>
    export type AdminInviteUserMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Invite User
 */
export const useAdminInviteUser = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminInviteUser>>, TError,{data: BodyType<InviteUserRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminInviteUser>>,
        TError,
        {data: BodyType<InviteUserRequest>},
        TContext
      > => {
      return useMutation(getAdminInviteUserMutationOptions(options), queryClient);
    }
    export type adminRevokeInvitationResponse204 = {
  data: void
  status: 204
}

export type adminRevokeInvitationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminRevokeInvitationResponseSuccess = (adminRevokeInvitationResponse204) & {
  headers: Headers;
};
export type adminRevokeInvitationResponseError = (adminRevokeInvitationResponse422) & {
  headers: Headers;
};

export type adminRevokeInvitationResponse = (adminRevokeInvitationResponseSuccess | adminRevokeInvitationResponseError)

export const getAdminRevokeInvitationUrl = (userId: number,) => {




  return `/api/v1/admin/users/${userId}/revoke-invitation`
}

/**
 * @summary Revoke Invitation
 */
export const adminRevokeInvitation = async (userId: number, options?: RequestInit): Promise<adminRevokeInvitationResponse> => {

  return mutator<adminRevokeInvitationResponse>(getAdminRevokeInvitationUrl(userId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminRevokeInvitationMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRevokeInvitation>>, TError,{userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminRevokeInvitation>>, TError,{userId: number}, TContext> => {

const mutationKey = ['adminRevokeInvitation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminRevokeInvitation>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  adminRevokeInvitation(userId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminRevokeInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof adminRevokeInvitation>>>

    export type AdminRevokeInvitationMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Revoke Invitation
 */
export const useAdminRevokeInvitation = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRevokeInvitation>>, TError,{userId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminRevokeInvitation>>,
        TError,
        {userId: number},
        TContext
      > => {
      return useMutation(getAdminRevokeInvitationMutationOptions(options), queryClient);
    }
