/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptInvitationRequest,
  BodyAuthLogin,
  ChangePasswordRequest,
  ForgotPasswordAck,
  ForgotPasswordRequest,
  HTTPValidationError,
  LoginResponse,
  MeResponse,
  RefreshResponse,
  ResetPasswordRequest,
  UpdateProfileRequest,
  VerifyOtpRequest,
  VerifyOtpResponse
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type authLoginResponse200 = {
  data: LoginResponse
  status: 200
}

export type authLoginResponse401 = {
  data: void
  status: 401
}

export type authLoginResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authLoginResponse429 = {
  data: void
  status: 429
}

export type authLoginResponseSuccess = (authLoginResponse200) & {
  headers: Headers;
};
export type authLoginResponseError = (authLoginResponse401 | authLoginResponse422 | authLoginResponse429) & {
  headers: Headers;
};

export type authLoginResponse = (authLoginResponseSuccess | authLoginResponseError)

export const getAuthLoginUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * @summary Login
 */
export const authLogin = async (bodyAuthLogin: BodyAuthLogin, options?: RequestInit): Promise<authLoginResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`username`, bodyAuthLogin.username);
formUrlEncoded.append(`password`, bodyAuthLogin.password);

  return mutator<authLoginResponse>(getAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
);}




export const getAuthLoginMutationOptions = <TError = ErrorType<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: BodyType<BodyAuthLogin>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: BodyType<BodyAuthLogin>}, TContext> => {

const mutationKey = ['authLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogin>>, {data: BodyType<BodyAuthLogin>}> = (props) => {
          const {data} = props ?? {};

          return  authLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
    export type AuthLoginMutationBody = BodyType<BodyAuthLogin>
    export type AuthLoginMutationError = ErrorType<void | HTTPValidationError>

    /**
 * @summary Login
 */
export const useAuthLogin = <TError = ErrorType<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: BodyType<BodyAuthLogin>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        {data: BodyType<BodyAuthLogin>},
        TContext
      > => {
      return useMutation(getAuthLoginMutationOptions(options), queryClient);
    }
    export type authLogoutResponse204 = {
  data: void
  status: 204
}

export type authLogoutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authLogoutResponseSuccess = (authLogoutResponse204) & {
  headers: Headers;
};
export type authLogoutResponseError = (authLogoutResponse422) & {
  headers: Headers;
};

export type authLogoutResponse = (authLogoutResponseSuccess | authLogoutResponseError)

export const getAuthLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * @summary Logout
 */
export const authLogout = async ( options?: RequestInit): Promise<authLogoutResponse> => {

  return mutator<authLogoutResponse>(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthLogoutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {


          return  authLogout()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>

    export type AuthLogoutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Logout
 */
export const useAuthLogout = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthLogoutMutationOptions(options), queryClient);
    }
    export type authRefreshResponse200 = {
  data: RefreshResponse
  status: 200
}

export type authRefreshResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authRefreshResponseSuccess = (authRefreshResponse200) & {
  headers: Headers;
};
export type authRefreshResponseError = (authRefreshResponse422) & {
  headers: Headers;
};

export type authRefreshResponse = (authRefreshResponseSuccess | authRefreshResponseError)

export const getAuthRefreshUrl = () => {




  return `/api/v1/auth/refresh`
}

/**
 * @summary Refresh
 */
export const authRefresh = async ( options?: RequestInit): Promise<authRefreshResponse> => {

  return mutator<authRefreshResponse>(getAuthRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthRefreshMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError,void, TContext> => {

const mutationKey = ['authRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRefresh>>, void> = () => {


          return  authRefresh()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authRefresh>>>

    export type AuthRefreshMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Refresh
 */
export const useAuthRefresh = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthRefreshMutationOptions(options), queryClient);
    }
    export type authMeResponse200 = {
  data: MeResponse
  status: 200
}

export type authMeResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authMeResponseSuccess = (authMeResponse200) & {
  headers: Headers;
};
export type authMeResponseError = (authMeResponse422) & {
  headers: Headers;
};

export type authMeResponse = (authMeResponseSuccess | authMeResponseError)

export const getAuthMeUrl = () => {




  return `/api/v1/auth/me`
}

/**
 * @summary Me
 */
export const authMe = async ( options?: RequestInit): Promise<authMeResponse> => {

  return mutator<authMeResponse>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuthMeQueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof authMe>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({ signal }) => authMe({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
export type AuthMeQueryError = ErrorType<HTTPValidationError>


export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Me
 */

export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type authUpdateProfileResponse200 = {
  data: MeResponse
  status: 200
}

export type authUpdateProfileResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authUpdateProfileResponseSuccess = (authUpdateProfileResponse200) & {
  headers: Headers;
};
export type authUpdateProfileResponseError = (authUpdateProfileResponse422) & {
  headers: Headers;
};

export type authUpdateProfileResponse = (authUpdateProfileResponseSuccess | authUpdateProfileResponseError)

export const getAuthUpdateProfileUrl = () => {




  return `/api/v1/auth/me`
}

/**
 * @summary Update My Profile
 */
export const authUpdateProfile = async (updateProfileRequest: UpdateProfileRequest, options?: RequestInit): Promise<authUpdateProfileResponse> => {

  return mutator<authUpdateProfileResponse>(getAuthUpdateProfileUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProfileRequest)
  }
);}




export const getAuthUpdateProfileMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authUpdateProfile>>, TError,{data: BodyType<UpdateProfileRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authUpdateProfile>>, TError,{data: BodyType<UpdateProfileRequest>}, TContext> => {

const mutationKey = ['authUpdateProfile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authUpdateProfile>>, {data: BodyType<UpdateProfileRequest>}> = (props) => {
          const {data} = props ?? {};

          return  authUpdateProfile(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthUpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof authUpdateProfile>>>
    export type AuthUpdateProfileMutationBody = BodyType<UpdateProfileRequest>
    export type AuthUpdateProfileMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update My Profile
 */
export const useAuthUpdateProfile = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authUpdateProfile>>, TError,{data: BodyType<UpdateProfileRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authUpdateProfile>>,
        TError,
        {data: BodyType<UpdateProfileRequest>},
        TContext
      > => {
      return useMutation(getAuthUpdateProfileMutationOptions(options), queryClient);
    }
    export type authChangePasswordResponse204 = {
  data: void
  status: 204
}

export type authChangePasswordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authChangePasswordResponseSuccess = (authChangePasswordResponse204) & {
  headers: Headers;
};
export type authChangePasswordResponseError = (authChangePasswordResponse422) & {
  headers: Headers;
};

export type authChangePasswordResponse = (authChangePasswordResponseSuccess | authChangePasswordResponseError)

export const getAuthChangePasswordUrl = () => {




  return `/api/v1/auth/change-password`
}

/**
 * @summary Change Password
 */
export const authChangePassword = async (changePasswordRequest: ChangePasswordRequest, options?: RequestInit): Promise<authChangePasswordResponse> => {

  return mutator<authChangePasswordResponse>(getAuthChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(changePasswordRequest)
  }
);}




export const getAuthChangePasswordMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authChangePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authChangePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext> => {

const mutationKey = ['authChangePassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authChangePassword>>, {data: BodyType<ChangePasswordRequest>}> = (props) => {
          const {data} = props ?? {};

          return  authChangePassword(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authChangePassword>>>
    export type AuthChangePasswordMutationBody = BodyType<ChangePasswordRequest>
    export type AuthChangePasswordMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Change Password
 */
export const useAuthChangePassword = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authChangePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authChangePassword>>,
        TError,
        {data: BodyType<ChangePasswordRequest>},
        TContext
      > => {
      return useMutation(getAuthChangePasswordMutationOptions(options), queryClient);
    }
    export type authForgotPasswordResponse202 = {
  data: ForgotPasswordAck
  status: 202
}

export type authForgotPasswordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authForgotPasswordResponseSuccess = (authForgotPasswordResponse202) & {
  headers: Headers;
};
export type authForgotPasswordResponseError = (authForgotPasswordResponse422) & {
  headers: Headers;
};

export type authForgotPasswordResponse = (authForgotPasswordResponseSuccess | authForgotPasswordResponseError)

export const getAuthForgotPasswordUrl = () => {




  return `/api/v1/auth/forgot-password`
}

/**
 * @summary Forgot Password
 */
export const authForgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<authForgotPasswordResponse> => {

  return mutator<authForgotPasswordResponse>(getAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(forgotPasswordRequest)
  }
);}




export const getAuthForgotPasswordMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authForgotPassword>>, TError,{data: BodyType<ForgotPasswordRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authForgotPassword>>, TError,{data: BodyType<ForgotPasswordRequest>}, TContext> => {

const mutationKey = ['authForgotPassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authForgotPassword>>, {data: BodyType<ForgotPasswordRequest>}> = (props) => {
          const {data} = props ?? {};

          return  authForgotPassword(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authForgotPassword>>>
    export type AuthForgotPasswordMutationBody = BodyType<ForgotPasswordRequest>
    export type AuthForgotPasswordMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Forgot Password
 */
export const useAuthForgotPassword = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authForgotPassword>>, TError,{data: BodyType<ForgotPasswordRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authForgotPassword>>,
        TError,
        {data: BodyType<ForgotPasswordRequest>},
        TContext
      > => {
      return useMutation(getAuthForgotPasswordMutationOptions(options), queryClient);
    }
    export type authVerifyOtpResponse200 = {
  data: VerifyOtpResponse
  status: 200
}

export type authVerifyOtpResponse400 = {
  data: void
  status: 400
}

export type authVerifyOtpResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authVerifyOtpResponseSuccess = (authVerifyOtpResponse200) & {
  headers: Headers;
};
export type authVerifyOtpResponseError = (authVerifyOtpResponse400 | authVerifyOtpResponse422) & {
  headers: Headers;
};

export type authVerifyOtpResponse = (authVerifyOtpResponseSuccess | authVerifyOtpResponseError)

export const getAuthVerifyOtpUrl = () => {




  return `/api/v1/auth/verify-otp`
}

/**
 * @summary Verify Otp
 */
export const authVerifyOtp = async (verifyOtpRequest: VerifyOtpRequest, options?: RequestInit): Promise<authVerifyOtpResponse> => {

  return mutator<authVerifyOtpResponse>(getAuthVerifyOtpUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(verifyOtpRequest)
  }
);}




export const getAuthVerifyOtpMutationOptions = <TError = ErrorType<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authVerifyOtp>>, TError,{data: BodyType<VerifyOtpRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authVerifyOtp>>, TError,{data: BodyType<VerifyOtpRequest>}, TContext> => {

const mutationKey = ['authVerifyOtp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authVerifyOtp>>, {data: BodyType<VerifyOtpRequest>}> = (props) => {
          const {data} = props ?? {};

          return  authVerifyOtp(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthVerifyOtpMutationResult = NonNullable<Awaited<ReturnType<typeof authVerifyOtp>>>
    export type AuthVerifyOtpMutationBody = BodyType<VerifyOtpRequest>
    export type AuthVerifyOtpMutationError = ErrorType<void | HTTPValidationError>

    /**
 * @summary Verify Otp
 */
export const useAuthVerifyOtp = <TError = ErrorType<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authVerifyOtp>>, TError,{data: BodyType<VerifyOtpRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authVerifyOtp>>,
        TError,
        {data: BodyType<VerifyOtpRequest>},
        TContext
      > => {
      return useMutation(getAuthVerifyOtpMutationOptions(options), queryClient);
    }
    export type authResetPasswordResponse200 = {
  data: LoginResponse
  status: 200
}

export type authResetPasswordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authResetPasswordResponseSuccess = (authResetPasswordResponse200) & {
  headers: Headers;
};
export type authResetPasswordResponseError = (authResetPasswordResponse422) & {
  headers: Headers;
};

export type authResetPasswordResponse = (authResetPasswordResponseSuccess | authResetPasswordResponseError)

export const getAuthResetPasswordUrl = () => {




  return `/api/v1/auth/reset-password`
}

/**
 * @summary Reset Password
 */
export const authResetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<authResetPasswordResponse> => {

  return mutator<authResetPasswordResponse>(getAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resetPasswordRequest)
  }
);}




export const getAuthResetPasswordMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authResetPassword>>, TError,{data: BodyType<ResetPasswordRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authResetPassword>>, TError,{data: BodyType<ResetPasswordRequest>}, TContext> => {

const mutationKey = ['authResetPassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authResetPassword>>, {data: BodyType<ResetPasswordRequest>}> = (props) => {
          const {data} = props ?? {};

          return  authResetPassword(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authResetPassword>>>
    export type AuthResetPasswordMutationBody = BodyType<ResetPasswordRequest>
    export type AuthResetPasswordMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Reset Password
 */
export const useAuthResetPassword = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authResetPassword>>, TError,{data: BodyType<ResetPasswordRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authResetPassword>>,
        TError,
        {data: BodyType<ResetPasswordRequest>},
        TContext
      > => {
      return useMutation(getAuthResetPasswordMutationOptions(options), queryClient);
    }
    export type authAcceptInvitationResponse200 = {
  data: LoginResponse
  status: 200
}

export type authAcceptInvitationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type authAcceptInvitationResponseSuccess = (authAcceptInvitationResponse200) & {
  headers: Headers;
};
export type authAcceptInvitationResponseError = (authAcceptInvitationResponse422) & {
  headers: Headers;
};

export type authAcceptInvitationResponse = (authAcceptInvitationResponseSuccess | authAcceptInvitationResponseError)

export const getAuthAcceptInvitationUrl = () => {




  return `/api/v1/auth/accept-invitation`
}

/**
 * @summary Accept Invitation
 */
export const authAcceptInvitation = async (acceptInvitationRequest: AcceptInvitationRequest, options?: RequestInit): Promise<authAcceptInvitationResponse> => {

  return mutator<authAcceptInvitationResponse>(getAuthAcceptInvitationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(acceptInvitationRequest)
  }
);}




export const getAuthAcceptInvitationMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAcceptInvitation>>, TError,{data: BodyType<AcceptInvitationRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authAcceptInvitation>>, TError,{data: BodyType<AcceptInvitationRequest>}, TContext> => {

const mutationKey = ['authAcceptInvitation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAcceptInvitation>>, {data: BodyType<AcceptInvitationRequest>}> = (props) => {
          const {data} = props ?? {};

          return  authAcceptInvitation(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAcceptInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof authAcceptInvitation>>>
    export type AuthAcceptInvitationMutationBody = BodyType<AcceptInvitationRequest>
    export type AuthAcceptInvitationMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Accept Invitation
 */
export const useAuthAcceptInvitation = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAcceptInvitation>>, TError,{data: BodyType<AcceptInvitationRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAcceptInvitation>>,
        TError,
        {data: BodyType<AcceptInvitationRequest>},
        TContext
      > => {
      return useMutation(getAuthAcceptInvitationMutationOptions(options), queryClient);
    }
