/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminDispatchDueRemindersParams,
  AdminLeadDuplicatesParams,
  AdminListClosureReasonsParams,
  AdminListDueRemindersParams,
  AdminListLeadSourcesParams,
  AdminListLeadsParams,
  ClosureReasonCreate,
  ClosureReasonOut,
  ClosureReasonUpdate,
  DispatchSummary,
  HTTPValidationError,
  LeadCreate,
  LeadDetail,
  LeadList,
  LeadListItem,
  LeadUpdate,
  NoteCreate,
  NoteOut,
  NoteUpdate,
  PipelineSummary,
  ReminderCreate,
  ReminderList,
  ReminderOut,
  ReminderUpdate,
  SourceCreate,
  SourceOut,
  SourceUpdate,
  StageChange
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListLeadsResponse200 = {
  data: LeadList
  status: 200
}

export type adminListLeadsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListLeadsResponseSuccess = (adminListLeadsResponse200) & {
  headers: Headers;
};
export type adminListLeadsResponseError = (adminListLeadsResponse422) & {
  headers: Headers;
};

export type adminListLeadsResponse = (adminListLeadsResponseSuccess | adminListLeadsResponseError)

export const getAdminListLeadsUrl = (params?: AdminListLeadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/crm/leads?${stringifiedParams}` : `/api/v1/admin/crm/leads`
}

/**
 * @summary List Leads
 */
export const adminListLeads = async (params?: AdminListLeadsParams, options?: RequestInit): Promise<adminListLeadsResponse> => {

  return mutator<adminListLeadsResponse>(getAdminListLeadsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListLeadsQueryKey = (params?: AdminListLeadsParams,) => {
    return [
    `/api/v1/admin/crm/leads`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListLeadsQueryOptions = <TData = Awaited<ReturnType<typeof adminListLeads>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeads>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListLeadsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListLeads>>> = ({ signal }) => adminListLeads(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListLeads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListLeadsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListLeads>>>
export type AdminListLeadsQueryError = ErrorType<HTTPValidationError>


export function useAdminListLeads<TData = Awaited<ReturnType<typeof adminListLeads>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListLeadsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeads>>,
          TError,
          Awaited<ReturnType<typeof adminListLeads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeads<TData = Awaited<ReturnType<typeof adminListLeads>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeads>>,
          TError,
          Awaited<ReturnType<typeof adminListLeads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeads<TData = Awaited<ReturnType<typeof adminListLeads>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeads>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Leads
 */

export function useAdminListLeads<TData = Awaited<ReturnType<typeof adminListLeads>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeads>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListLeadsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateLeadResponse201 = {
  data: LeadDetail
  status: 201
}

export type adminCreateLeadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateLeadResponseSuccess = (adminCreateLeadResponse201) & {
  headers: Headers;
};
export type adminCreateLeadResponseError = (adminCreateLeadResponse422) & {
  headers: Headers;
};

export type adminCreateLeadResponse = (adminCreateLeadResponseSuccess | adminCreateLeadResponseError)

export const getAdminCreateLeadUrl = () => {




  return `/api/v1/admin/crm/leads`
}

/**
 * @summary Create Lead
 */
export const adminCreateLead = async (leadCreate: LeadCreate, options?: RequestInit): Promise<adminCreateLeadResponse> => {

  return mutator<adminCreateLeadResponse>(getAdminCreateLeadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(leadCreate)
  }
);}




export const getAdminCreateLeadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateLead>>, TError,{data: BodyType<LeadCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateLead>>, TError,{data: BodyType<LeadCreate>}, TContext> => {

const mutationKey = ['adminCreateLead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateLead>>, {data: BodyType<LeadCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateLead(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateLeadMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateLead>>>
    export type AdminCreateLeadMutationBody = BodyType<LeadCreate>
    export type AdminCreateLeadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Lead
 */
export const useAdminCreateLead = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateLead>>, TError,{data: BodyType<LeadCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateLead>>,
        TError,
        {data: BodyType<LeadCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateLeadMutationOptions(options), queryClient);
    }
    export type adminLeadSummaryResponse200 = {
  data: PipelineSummary
  status: 200
}

export type adminLeadSummaryResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminLeadSummaryResponseSuccess = (adminLeadSummaryResponse200) & {
  headers: Headers;
};
export type adminLeadSummaryResponseError = (adminLeadSummaryResponse422) & {
  headers: Headers;
};

export type adminLeadSummaryResponse = (adminLeadSummaryResponseSuccess | adminLeadSummaryResponseError)

export const getAdminLeadSummaryUrl = () => {




  return `/api/v1/admin/crm/leads/summary`
}

/**
 * @summary Lead Summary
 */
export const adminLeadSummary = async ( options?: RequestInit): Promise<adminLeadSummaryResponse> => {

  return mutator<adminLeadSummaryResponse>(getAdminLeadSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminLeadSummaryQueryKey = () => {
    return [
    `/api/v1/admin/crm/leads/summary`
    ] as const;
    }


export const getAdminLeadSummaryQueryOptions = <TData = Awaited<ReturnType<typeof adminLeadSummary>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminLeadSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminLeadSummary>>> = ({ signal }) => adminLeadSummary({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminLeadSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminLeadSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof adminLeadSummary>>>
export type AdminLeadSummaryQueryError = ErrorType<HTTPValidationError>


export function useAdminLeadSummary<TData = Awaited<ReturnType<typeof adminLeadSummary>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminLeadSummary>>,
          TError,
          Awaited<ReturnType<typeof adminLeadSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminLeadSummary<TData = Awaited<ReturnType<typeof adminLeadSummary>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminLeadSummary>>,
          TError,
          Awaited<ReturnType<typeof adminLeadSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminLeadSummary<TData = Awaited<ReturnType<typeof adminLeadSummary>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lead Summary
 */

export function useAdminLeadSummary<TData = Awaited<ReturnType<typeof adminLeadSummary>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminLeadSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminLeadDuplicatesResponse200 = {
  data: LeadListItem[]
  status: 200
}

export type adminLeadDuplicatesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminLeadDuplicatesResponseSuccess = (adminLeadDuplicatesResponse200) & {
  headers: Headers;
};
export type adminLeadDuplicatesResponseError = (adminLeadDuplicatesResponse422) & {
  headers: Headers;
};

export type adminLeadDuplicatesResponse = (adminLeadDuplicatesResponseSuccess | adminLeadDuplicatesResponseError)

export const getAdminLeadDuplicatesUrl = (params?: AdminLeadDuplicatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/crm/leads/duplicates?${stringifiedParams}` : `/api/v1/admin/crm/leads/duplicates`
}

/**
 * @summary Lead Duplicates
 */
export const adminLeadDuplicates = async (params?: AdminLeadDuplicatesParams, options?: RequestInit): Promise<adminLeadDuplicatesResponse> => {

  return mutator<adminLeadDuplicatesResponse>(getAdminLeadDuplicatesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminLeadDuplicatesQueryKey = (params?: AdminLeadDuplicatesParams,) => {
    return [
    `/api/v1/admin/crm/leads/duplicates`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminLeadDuplicatesQueryOptions = <TData = Awaited<ReturnType<typeof adminLeadDuplicates>>, TError = ErrorType<HTTPValidationError>>(params?: AdminLeadDuplicatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadDuplicates>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminLeadDuplicatesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminLeadDuplicates>>> = ({ signal }) => adminLeadDuplicates(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminLeadDuplicates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminLeadDuplicatesQueryResult = NonNullable<Awaited<ReturnType<typeof adminLeadDuplicates>>>
export type AdminLeadDuplicatesQueryError = ErrorType<HTTPValidationError>


export function useAdminLeadDuplicates<TData = Awaited<ReturnType<typeof adminLeadDuplicates>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminLeadDuplicatesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadDuplicates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminLeadDuplicates>>,
          TError,
          Awaited<ReturnType<typeof adminLeadDuplicates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminLeadDuplicates<TData = Awaited<ReturnType<typeof adminLeadDuplicates>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminLeadDuplicatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadDuplicates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminLeadDuplicates>>,
          TError,
          Awaited<ReturnType<typeof adminLeadDuplicates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminLeadDuplicates<TData = Awaited<ReturnType<typeof adminLeadDuplicates>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminLeadDuplicatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadDuplicates>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lead Duplicates
 */

export function useAdminLeadDuplicates<TData = Awaited<ReturnType<typeof adminLeadDuplicates>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminLeadDuplicatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLeadDuplicates>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminLeadDuplicatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminGetLeadResponse200 = {
  data: LeadDetail
  status: 200
}

export type adminGetLeadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetLeadResponseSuccess = (adminGetLeadResponse200) & {
  headers: Headers;
};
export type adminGetLeadResponseError = (adminGetLeadResponse422) & {
  headers: Headers;
};

export type adminGetLeadResponse = (adminGetLeadResponseSuccess | adminGetLeadResponseError)

export const getAdminGetLeadUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}`
}

/**
 * @summary Get Lead
 */
export const adminGetLead = async (leadUuid: string, options?: RequestInit): Promise<adminGetLeadResponse> => {

  return mutator<adminGetLeadResponse>(getAdminGetLeadUrl(leadUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetLeadQueryKey = (leadUuid: string,) => {
    return [
    `/api/v1/admin/crm/leads/${leadUuid}`
    ] as const;
    }


export const getAdminGetLeadQueryOptions = <TData = Awaited<ReturnType<typeof adminGetLead>>, TError = ErrorType<HTTPValidationError>>(leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetLead>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetLeadQueryKey(leadUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetLead>>> = ({ signal }) => adminGetLead(leadUuid, { signal });





   return  { queryKey, queryFn, enabled: leadUuid !== null && leadUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetLead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetLeadQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetLead>>>
export type AdminGetLeadQueryError = ErrorType<HTTPValidationError>


export function useAdminGetLead<TData = Awaited<ReturnType<typeof adminGetLead>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetLead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetLead>>,
          TError,
          Awaited<ReturnType<typeof adminGetLead>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetLead<TData = Awaited<ReturnType<typeof adminGetLead>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetLead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetLead>>,
          TError,
          Awaited<ReturnType<typeof adminGetLead>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetLead<TData = Awaited<ReturnType<typeof adminGetLead>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetLead>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Lead
 */

export function useAdminGetLead<TData = Awaited<ReturnType<typeof adminGetLead>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetLead>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetLeadQueryOptions(leadUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdateLeadResponse200 = {
  data: LeadDetail
  status: 200
}

export type adminUpdateLeadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateLeadResponseSuccess = (adminUpdateLeadResponse200) & {
  headers: Headers;
};
export type adminUpdateLeadResponseError = (adminUpdateLeadResponse422) & {
  headers: Headers;
};

export type adminUpdateLeadResponse = (adminUpdateLeadResponseSuccess | adminUpdateLeadResponseError)

export const getAdminUpdateLeadUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}`
}

/**
 * @summary Update Lead
 */
export const adminUpdateLead = async (leadUuid: string,
    leadUpdate: LeadUpdate, options?: RequestInit): Promise<adminUpdateLeadResponse> => {

  return mutator<adminUpdateLeadResponse>(getAdminUpdateLeadUrl(leadUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(leadUpdate)
  }
);}




export const getAdminUpdateLeadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLead>>, TError,{leadUuid: string;data: BodyType<LeadUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLead>>, TError,{leadUuid: string;data: BodyType<LeadUpdate>}, TContext> => {

const mutationKey = ['adminUpdateLead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateLead>>, {leadUuid: string;data: BodyType<LeadUpdate>}> = (props) => {
          const {leadUuid,data} = props ?? {};

          return  adminUpdateLead(leadUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateLeadMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateLead>>>
    export type AdminUpdateLeadMutationBody = BodyType<LeadUpdate>
    export type AdminUpdateLeadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Lead
 */
export const useAdminUpdateLead = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLead>>, TError,{leadUuid: string;data: BodyType<LeadUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateLead>>,
        TError,
        {leadUuid: string;data: BodyType<LeadUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateLeadMutationOptions(options), queryClient);
    }
    export type adminDeleteLeadResponse204 = {
  data: void
  status: 204
}

export type adminDeleteLeadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteLeadResponseSuccess = (adminDeleteLeadResponse204) & {
  headers: Headers;
};
export type adminDeleteLeadResponseError = (adminDeleteLeadResponse422) & {
  headers: Headers;
};

export type adminDeleteLeadResponse = (adminDeleteLeadResponseSuccess | adminDeleteLeadResponseError)

export const getAdminDeleteLeadUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}`
}

/**
 * @summary Delete Lead
 */
export const adminDeleteLead = async (leadUuid: string, options?: RequestInit): Promise<adminDeleteLeadResponse> => {

  return mutator<adminDeleteLeadResponse>(getAdminDeleteLeadUrl(leadUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeleteLeadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteLead>>, TError,{leadUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteLead>>, TError,{leadUuid: string}, TContext> => {

const mutationKey = ['adminDeleteLead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteLead>>, {leadUuid: string}> = (props) => {
          const {leadUuid} = props ?? {};

          return  adminDeleteLead(leadUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteLeadMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteLead>>>

    export type AdminDeleteLeadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Lead
 */
export const useAdminDeleteLead = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteLead>>, TError,{leadUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteLead>>,
        TError,
        {leadUuid: string},
        TContext
      > => {
      return useMutation(getAdminDeleteLeadMutationOptions(options), queryClient);
    }
    export type adminListLeadNotesResponse200 = {
  data: NoteOut[]
  status: 200
}

export type adminListLeadNotesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListLeadNotesResponseSuccess = (adminListLeadNotesResponse200) & {
  headers: Headers;
};
export type adminListLeadNotesResponseError = (adminListLeadNotesResponse422) & {
  headers: Headers;
};

export type adminListLeadNotesResponse = (adminListLeadNotesResponseSuccess | adminListLeadNotesResponseError)

export const getAdminListLeadNotesUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}/notes`
}

/**
 * @summary List Lead Notes
 */
export const adminListLeadNotes = async (leadUuid: string, options?: RequestInit): Promise<adminListLeadNotesResponse> => {

  return mutator<adminListLeadNotesResponse>(getAdminListLeadNotesUrl(leadUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListLeadNotesQueryKey = (leadUuid: string,) => {
    return [
    `/api/v1/admin/crm/leads/${leadUuid}/notes`
    ] as const;
    }


export const getAdminListLeadNotesQueryOptions = <TData = Awaited<ReturnType<typeof adminListLeadNotes>>, TError = ErrorType<HTTPValidationError>>(leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadNotes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListLeadNotesQueryKey(leadUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListLeadNotes>>> = ({ signal }) => adminListLeadNotes(leadUuid, { signal });





   return  { queryKey, queryFn, enabled: leadUuid !== null && leadUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListLeadNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListLeadNotesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListLeadNotes>>>
export type AdminListLeadNotesQueryError = ErrorType<HTTPValidationError>


export function useAdminListLeadNotes<TData = Awaited<ReturnType<typeof adminListLeadNotes>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeadNotes>>,
          TError,
          Awaited<ReturnType<typeof adminListLeadNotes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeadNotes<TData = Awaited<ReturnType<typeof adminListLeadNotes>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeadNotes>>,
          TError,
          Awaited<ReturnType<typeof adminListLeadNotes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeadNotes<TData = Awaited<ReturnType<typeof adminListLeadNotes>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadNotes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Lead Notes
 */

export function useAdminListLeadNotes<TData = Awaited<ReturnType<typeof adminListLeadNotes>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadNotes>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListLeadNotesQueryOptions(leadUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminAddLeadNoteResponse201 = {
  data: NoteOut
  status: 201
}

export type adminAddLeadNoteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAddLeadNoteResponseSuccess = (adminAddLeadNoteResponse201) & {
  headers: Headers;
};
export type adminAddLeadNoteResponseError = (adminAddLeadNoteResponse422) & {
  headers: Headers;
};

export type adminAddLeadNoteResponse = (adminAddLeadNoteResponseSuccess | adminAddLeadNoteResponseError)

export const getAdminAddLeadNoteUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}/notes`
}

/**
 * @summary Add Lead Note
 */
export const adminAddLeadNote = async (leadUuid: string,
    noteCreate: NoteCreate, options?: RequestInit): Promise<adminAddLeadNoteResponse> => {

  return mutator<adminAddLeadNoteResponse>(getAdminAddLeadNoteUrl(leadUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(noteCreate)
  }
);}




export const getAdminAddLeadNoteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddLeadNote>>, TError,{leadUuid: string;data: BodyType<NoteCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAddLeadNote>>, TError,{leadUuid: string;data: BodyType<NoteCreate>}, TContext> => {

const mutationKey = ['adminAddLeadNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAddLeadNote>>, {leadUuid: string;data: BodyType<NoteCreate>}> = (props) => {
          const {leadUuid,data} = props ?? {};

          return  adminAddLeadNote(leadUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminAddLeadNoteMutationResult = NonNullable<Awaited<ReturnType<typeof adminAddLeadNote>>>
    export type AdminAddLeadNoteMutationBody = BodyType<NoteCreate>
    export type AdminAddLeadNoteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add Lead Note
 */
export const useAdminAddLeadNote = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddLeadNote>>, TError,{leadUuid: string;data: BodyType<NoteCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAddLeadNote>>,
        TError,
        {leadUuid: string;data: BodyType<NoteCreate>},
        TContext
      > => {
      return useMutation(getAdminAddLeadNoteMutationOptions(options), queryClient);
    }
    export type adminListLeadRemindersResponse200 = {
  data: ReminderOut[]
  status: 200
}

export type adminListLeadRemindersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListLeadRemindersResponseSuccess = (adminListLeadRemindersResponse200) & {
  headers: Headers;
};
export type adminListLeadRemindersResponseError = (adminListLeadRemindersResponse422) & {
  headers: Headers;
};

export type adminListLeadRemindersResponse = (adminListLeadRemindersResponseSuccess | adminListLeadRemindersResponseError)

export const getAdminListLeadRemindersUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}/reminders`
}

/**
 * @summary List Lead Reminders
 */
export const adminListLeadReminders = async (leadUuid: string, options?: RequestInit): Promise<adminListLeadRemindersResponse> => {

  return mutator<adminListLeadRemindersResponse>(getAdminListLeadRemindersUrl(leadUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListLeadRemindersQueryKey = (leadUuid: string,) => {
    return [
    `/api/v1/admin/crm/leads/${leadUuid}/reminders`
    ] as const;
    }


export const getAdminListLeadRemindersQueryOptions = <TData = Awaited<ReturnType<typeof adminListLeadReminders>>, TError = ErrorType<HTTPValidationError>>(leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadReminders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListLeadRemindersQueryKey(leadUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListLeadReminders>>> = ({ signal }) => adminListLeadReminders(leadUuid, { signal });





   return  { queryKey, queryFn, enabled: leadUuid !== null && leadUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListLeadReminders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListLeadRemindersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListLeadReminders>>>
export type AdminListLeadRemindersQueryError = ErrorType<HTTPValidationError>


export function useAdminListLeadReminders<TData = Awaited<ReturnType<typeof adminListLeadReminders>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadReminders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeadReminders>>,
          TError,
          Awaited<ReturnType<typeof adminListLeadReminders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeadReminders<TData = Awaited<ReturnType<typeof adminListLeadReminders>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadReminders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeadReminders>>,
          TError,
          Awaited<ReturnType<typeof adminListLeadReminders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeadReminders<TData = Awaited<ReturnType<typeof adminListLeadReminders>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadReminders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Lead Reminders
 */

export function useAdminListLeadReminders<TData = Awaited<ReturnType<typeof adminListLeadReminders>>, TError = ErrorType<HTTPValidationError>>(
 leadUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadReminders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListLeadRemindersQueryOptions(leadUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateLeadReminderResponse201 = {
  data: ReminderOut
  status: 201
}

export type adminCreateLeadReminderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateLeadReminderResponseSuccess = (adminCreateLeadReminderResponse201) & {
  headers: Headers;
};
export type adminCreateLeadReminderResponseError = (adminCreateLeadReminderResponse422) & {
  headers: Headers;
};

export type adminCreateLeadReminderResponse = (adminCreateLeadReminderResponseSuccess | adminCreateLeadReminderResponseError)

export const getAdminCreateLeadReminderUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}/reminders`
}

/**
 * @summary Create Lead Reminder
 */
export const adminCreateLeadReminder = async (leadUuid: string,
    reminderCreate: ReminderCreate, options?: RequestInit): Promise<adminCreateLeadReminderResponse> => {

  return mutator<adminCreateLeadReminderResponse>(getAdminCreateLeadReminderUrl(leadUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reminderCreate)
  }
);}




export const getAdminCreateLeadReminderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateLeadReminder>>, TError,{leadUuid: string;data: BodyType<ReminderCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateLeadReminder>>, TError,{leadUuid: string;data: BodyType<ReminderCreate>}, TContext> => {

const mutationKey = ['adminCreateLeadReminder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateLeadReminder>>, {leadUuid: string;data: BodyType<ReminderCreate>}> = (props) => {
          const {leadUuid,data} = props ?? {};

          return  adminCreateLeadReminder(leadUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateLeadReminderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateLeadReminder>>>
    export type AdminCreateLeadReminderMutationBody = BodyType<ReminderCreate>
    export type AdminCreateLeadReminderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Lead Reminder
 */
export const useAdminCreateLeadReminder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateLeadReminder>>, TError,{leadUuid: string;data: BodyType<ReminderCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateLeadReminder>>,
        TError,
        {leadUuid: string;data: BodyType<ReminderCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateLeadReminderMutationOptions(options), queryClient);
    }
    export type adminChangeLeadStageResponse200 = {
  data: LeadDetail
  status: 200
}

export type adminChangeLeadStageResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminChangeLeadStageResponseSuccess = (adminChangeLeadStageResponse200) & {
  headers: Headers;
};
export type adminChangeLeadStageResponseError = (adminChangeLeadStageResponse422) & {
  headers: Headers;
};

export type adminChangeLeadStageResponse = (adminChangeLeadStageResponseSuccess | adminChangeLeadStageResponseError)

export const getAdminChangeLeadStageUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}/stage`
}

/**
 * @summary Change Lead Stage
 */
export const adminChangeLeadStage = async (leadUuid: string,
    stageChange: StageChange, options?: RequestInit): Promise<adminChangeLeadStageResponse> => {

  return mutator<adminChangeLeadStageResponse>(getAdminChangeLeadStageUrl(leadUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(stageChange)
  }
);}




export const getAdminChangeLeadStageMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminChangeLeadStage>>, TError,{leadUuid: string;data: BodyType<StageChange>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminChangeLeadStage>>, TError,{leadUuid: string;data: BodyType<StageChange>}, TContext> => {

const mutationKey = ['adminChangeLeadStage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminChangeLeadStage>>, {leadUuid: string;data: BodyType<StageChange>}> = (props) => {
          const {leadUuid,data} = props ?? {};

          return  adminChangeLeadStage(leadUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminChangeLeadStageMutationResult = NonNullable<Awaited<ReturnType<typeof adminChangeLeadStage>>>
    export type AdminChangeLeadStageMutationBody = BodyType<StageChange>
    export type AdminChangeLeadStageMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Change Lead Stage
 */
export const useAdminChangeLeadStage = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminChangeLeadStage>>, TError,{leadUuid: string;data: BodyType<StageChange>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminChangeLeadStage>>,
        TError,
        {leadUuid: string;data: BodyType<StageChange>},
        TContext
      > => {
      return useMutation(getAdminChangeLeadStageMutationOptions(options), queryClient);
    }
    export type adminReopenLeadResponse200 = {
  data: LeadDetail
  status: 200
}

export type adminReopenLeadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminReopenLeadResponseSuccess = (adminReopenLeadResponse200) & {
  headers: Headers;
};
export type adminReopenLeadResponseError = (adminReopenLeadResponse422) & {
  headers: Headers;
};

export type adminReopenLeadResponse = (adminReopenLeadResponseSuccess | adminReopenLeadResponseError)

export const getAdminReopenLeadUrl = (leadUuid: string,) => {




  return `/api/v1/admin/crm/leads/${leadUuid}/reopen`
}

/**
 * @summary Reopen Lead
 */
export const adminReopenLead = async (leadUuid: string, options?: RequestInit): Promise<adminReopenLeadResponse> => {

  return mutator<adminReopenLeadResponse>(getAdminReopenLeadUrl(leadUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminReopenLeadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminReopenLead>>, TError,{leadUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminReopenLead>>, TError,{leadUuid: string}, TContext> => {

const mutationKey = ['adminReopenLead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminReopenLead>>, {leadUuid: string}> = (props) => {
          const {leadUuid} = props ?? {};

          return  adminReopenLead(leadUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminReopenLeadMutationResult = NonNullable<Awaited<ReturnType<typeof adminReopenLead>>>

    export type AdminReopenLeadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Reopen Lead
 */
export const useAdminReopenLead = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminReopenLead>>, TError,{leadUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminReopenLead>>,
        TError,
        {leadUuid: string},
        TContext
      > => {
      return useMutation(getAdminReopenLeadMutationOptions(options), queryClient);
    }
    export type adminUpdateLeadNoteResponse200 = {
  data: NoteOut
  status: 200
}

export type adminUpdateLeadNoteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateLeadNoteResponseSuccess = (adminUpdateLeadNoteResponse200) & {
  headers: Headers;
};
export type adminUpdateLeadNoteResponseError = (adminUpdateLeadNoteResponse422) & {
  headers: Headers;
};

export type adminUpdateLeadNoteResponse = (adminUpdateLeadNoteResponseSuccess | adminUpdateLeadNoteResponseError)

export const getAdminUpdateLeadNoteUrl = (noteUuid: string,) => {




  return `/api/v1/admin/crm/notes/${noteUuid}`
}

/**
 * @summary Update Lead Note
 */
export const adminUpdateLeadNote = async (noteUuid: string,
    noteUpdate: NoteUpdate, options?: RequestInit): Promise<adminUpdateLeadNoteResponse> => {

  return mutator<adminUpdateLeadNoteResponse>(getAdminUpdateLeadNoteUrl(noteUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(noteUpdate)
  }
);}




export const getAdminUpdateLeadNoteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLeadNote>>, TError,{noteUuid: string;data: BodyType<NoteUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLeadNote>>, TError,{noteUuid: string;data: BodyType<NoteUpdate>}, TContext> => {

const mutationKey = ['adminUpdateLeadNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateLeadNote>>, {noteUuid: string;data: BodyType<NoteUpdate>}> = (props) => {
          const {noteUuid,data} = props ?? {};

          return  adminUpdateLeadNote(noteUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateLeadNoteMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateLeadNote>>>
    export type AdminUpdateLeadNoteMutationBody = BodyType<NoteUpdate>
    export type AdminUpdateLeadNoteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Lead Note
 */
export const useAdminUpdateLeadNote = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLeadNote>>, TError,{noteUuid: string;data: BodyType<NoteUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateLeadNote>>,
        TError,
        {noteUuid: string;data: BodyType<NoteUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateLeadNoteMutationOptions(options), queryClient);
    }
    export type adminDeleteLeadNoteResponse204 = {
  data: void
  status: 204
}

export type adminDeleteLeadNoteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteLeadNoteResponseSuccess = (adminDeleteLeadNoteResponse204) & {
  headers: Headers;
};
export type adminDeleteLeadNoteResponseError = (adminDeleteLeadNoteResponse422) & {
  headers: Headers;
};

export type adminDeleteLeadNoteResponse = (adminDeleteLeadNoteResponseSuccess | adminDeleteLeadNoteResponseError)

export const getAdminDeleteLeadNoteUrl = (noteUuid: string,) => {




  return `/api/v1/admin/crm/notes/${noteUuid}`
}

/**
 * @summary Delete Lead Note
 */
export const adminDeleteLeadNote = async (noteUuid: string, options?: RequestInit): Promise<adminDeleteLeadNoteResponse> => {

  return mutator<adminDeleteLeadNoteResponse>(getAdminDeleteLeadNoteUrl(noteUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeleteLeadNoteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteLeadNote>>, TError,{noteUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteLeadNote>>, TError,{noteUuid: string}, TContext> => {

const mutationKey = ['adminDeleteLeadNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteLeadNote>>, {noteUuid: string}> = (props) => {
          const {noteUuid} = props ?? {};

          return  adminDeleteLeadNote(noteUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteLeadNoteMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteLeadNote>>>

    export type AdminDeleteLeadNoteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Lead Note
 */
export const useAdminDeleteLeadNote = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteLeadNote>>, TError,{noteUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteLeadNote>>,
        TError,
        {noteUuid: string},
        TContext
      > => {
      return useMutation(getAdminDeleteLeadNoteMutationOptions(options), queryClient);
    }
    export type adminListDueRemindersResponse200 = {
  data: ReminderList
  status: 200
}

export type adminListDueRemindersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListDueRemindersResponseSuccess = (adminListDueRemindersResponse200) & {
  headers: Headers;
};
export type adminListDueRemindersResponseError = (adminListDueRemindersResponse422) & {
  headers: Headers;
};

export type adminListDueRemindersResponse = (adminListDueRemindersResponseSuccess | adminListDueRemindersResponseError)

export const getAdminListDueRemindersUrl = (params?: AdminListDueRemindersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/crm/reminders?${stringifiedParams}` : `/api/v1/admin/crm/reminders`
}

/**
 * @summary List Due Reminders
 */
export const adminListDueReminders = async (params?: AdminListDueRemindersParams, options?: RequestInit): Promise<adminListDueRemindersResponse> => {

  return mutator<adminListDueRemindersResponse>(getAdminListDueRemindersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListDueRemindersQueryKey = (params?: AdminListDueRemindersParams,) => {
    return [
    `/api/v1/admin/crm/reminders`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListDueRemindersQueryOptions = <TData = Awaited<ReturnType<typeof adminListDueReminders>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListDueRemindersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListDueReminders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListDueRemindersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListDueReminders>>> = ({ signal }) => adminListDueReminders(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListDueReminders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListDueRemindersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListDueReminders>>>
export type AdminListDueRemindersQueryError = ErrorType<HTTPValidationError>


export function useAdminListDueReminders<TData = Awaited<ReturnType<typeof adminListDueReminders>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListDueRemindersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListDueReminders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListDueReminders>>,
          TError,
          Awaited<ReturnType<typeof adminListDueReminders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListDueReminders<TData = Awaited<ReturnType<typeof adminListDueReminders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListDueRemindersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListDueReminders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListDueReminders>>,
          TError,
          Awaited<ReturnType<typeof adminListDueReminders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListDueReminders<TData = Awaited<ReturnType<typeof adminListDueReminders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListDueRemindersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListDueReminders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Due Reminders
 */

export function useAdminListDueReminders<TData = Awaited<ReturnType<typeof adminListDueReminders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListDueRemindersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListDueReminders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListDueRemindersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminDispatchDueRemindersResponse200 = {
  data: DispatchSummary
  status: 200
}

export type adminDispatchDueRemindersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDispatchDueRemindersResponseSuccess = (adminDispatchDueRemindersResponse200) & {
  headers: Headers;
};
export type adminDispatchDueRemindersResponseError = (adminDispatchDueRemindersResponse422) & {
  headers: Headers;
};

export type adminDispatchDueRemindersResponse = (adminDispatchDueRemindersResponseSuccess | adminDispatchDueRemindersResponseError)

export const getAdminDispatchDueRemindersUrl = (params?: AdminDispatchDueRemindersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/crm/reminders/dispatch-due?${stringifiedParams}` : `/api/v1/admin/crm/reminders/dispatch-due`
}

/**
 * @summary Dispatch Due Reminders
 */
export const adminDispatchDueReminders = async (params?: AdminDispatchDueRemindersParams, options?: RequestInit): Promise<adminDispatchDueRemindersResponse> => {

  return mutator<adminDispatchDueRemindersResponse>(getAdminDispatchDueRemindersUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminDispatchDueRemindersMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDispatchDueReminders>>, TError,{params?: AdminDispatchDueRemindersParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDispatchDueReminders>>, TError,{params?: AdminDispatchDueRemindersParams}, TContext> => {

const mutationKey = ['adminDispatchDueReminders'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDispatchDueReminders>>, {params?: AdminDispatchDueRemindersParams}> = (props) => {
          const {params} = props ?? {};

          return  adminDispatchDueReminders(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDispatchDueRemindersMutationResult = NonNullable<Awaited<ReturnType<typeof adminDispatchDueReminders>>>

    export type AdminDispatchDueRemindersMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Dispatch Due Reminders
 */
export const useAdminDispatchDueReminders = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDispatchDueReminders>>, TError,{params?: AdminDispatchDueRemindersParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDispatchDueReminders>>,
        TError,
        {params?: AdminDispatchDueRemindersParams},
        TContext
      > => {
      return useMutation(getAdminDispatchDueRemindersMutationOptions(options), queryClient);
    }
    export type adminUpdateReminderResponse200 = {
  data: ReminderOut
  status: 200
}

export type adminUpdateReminderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateReminderResponseSuccess = (adminUpdateReminderResponse200) & {
  headers: Headers;
};
export type adminUpdateReminderResponseError = (adminUpdateReminderResponse422) & {
  headers: Headers;
};

export type adminUpdateReminderResponse = (adminUpdateReminderResponseSuccess | adminUpdateReminderResponseError)

export const getAdminUpdateReminderUrl = (reminderUuid: string,) => {




  return `/api/v1/admin/crm/reminders/${reminderUuid}`
}

/**
 * @summary Update Reminder
 */
export const adminUpdateReminder = async (reminderUuid: string,
    reminderUpdate: ReminderUpdate, options?: RequestInit): Promise<adminUpdateReminderResponse> => {

  return mutator<adminUpdateReminderResponse>(getAdminUpdateReminderUrl(reminderUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reminderUpdate)
  }
);}




export const getAdminUpdateReminderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateReminder>>, TError,{reminderUuid: string;data: BodyType<ReminderUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateReminder>>, TError,{reminderUuid: string;data: BodyType<ReminderUpdate>}, TContext> => {

const mutationKey = ['adminUpdateReminder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateReminder>>, {reminderUuid: string;data: BodyType<ReminderUpdate>}> = (props) => {
          const {reminderUuid,data} = props ?? {};

          return  adminUpdateReminder(reminderUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateReminderMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateReminder>>>
    export type AdminUpdateReminderMutationBody = BodyType<ReminderUpdate>
    export type AdminUpdateReminderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Reminder
 */
export const useAdminUpdateReminder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateReminder>>, TError,{reminderUuid: string;data: BodyType<ReminderUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateReminder>>,
        TError,
        {reminderUuid: string;data: BodyType<ReminderUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateReminderMutationOptions(options), queryClient);
    }
    export type adminCompleteReminderResponse200 = {
  data: ReminderOut
  status: 200
}

export type adminCompleteReminderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCompleteReminderResponseSuccess = (adminCompleteReminderResponse200) & {
  headers: Headers;
};
export type adminCompleteReminderResponseError = (adminCompleteReminderResponse422) & {
  headers: Headers;
};

export type adminCompleteReminderResponse = (adminCompleteReminderResponseSuccess | adminCompleteReminderResponseError)

export const getAdminCompleteReminderUrl = (reminderUuid: string,) => {




  return `/api/v1/admin/crm/reminders/${reminderUuid}/complete`
}

/**
 * @summary Complete Reminder
 */
export const adminCompleteReminder = async (reminderUuid: string, options?: RequestInit): Promise<adminCompleteReminderResponse> => {

  return mutator<adminCompleteReminderResponse>(getAdminCompleteReminderUrl(reminderUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminCompleteReminderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteReminder>>, TError,{reminderUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCompleteReminder>>, TError,{reminderUuid: string}, TContext> => {

const mutationKey = ['adminCompleteReminder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCompleteReminder>>, {reminderUuid: string}> = (props) => {
          const {reminderUuid} = props ?? {};

          return  adminCompleteReminder(reminderUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCompleteReminderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCompleteReminder>>>

    export type AdminCompleteReminderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Complete Reminder
 */
export const useAdminCompleteReminder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteReminder>>, TError,{reminderUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCompleteReminder>>,
        TError,
        {reminderUuid: string},
        TContext
      > => {
      return useMutation(getAdminCompleteReminderMutationOptions(options), queryClient);
    }
    export type adminCancelReminderResponse200 = {
  data: ReminderOut
  status: 200
}

export type adminCancelReminderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCancelReminderResponseSuccess = (adminCancelReminderResponse200) & {
  headers: Headers;
};
export type adminCancelReminderResponseError = (adminCancelReminderResponse422) & {
  headers: Headers;
};

export type adminCancelReminderResponse = (adminCancelReminderResponseSuccess | adminCancelReminderResponseError)

export const getAdminCancelReminderUrl = (reminderUuid: string,) => {




  return `/api/v1/admin/crm/reminders/${reminderUuid}/cancel`
}

/**
 * @summary Cancel Reminder
 */
export const adminCancelReminder = async (reminderUuid: string, options?: RequestInit): Promise<adminCancelReminderResponse> => {

  return mutator<adminCancelReminderResponse>(getAdminCancelReminderUrl(reminderUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminCancelReminderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelReminder>>, TError,{reminderUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCancelReminder>>, TError,{reminderUuid: string}, TContext> => {

const mutationKey = ['adminCancelReminder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCancelReminder>>, {reminderUuid: string}> = (props) => {
          const {reminderUuid} = props ?? {};

          return  adminCancelReminder(reminderUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCancelReminderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCancelReminder>>>

    export type AdminCancelReminderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Cancel Reminder
 */
export const useAdminCancelReminder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelReminder>>, TError,{reminderUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCancelReminder>>,
        TError,
        {reminderUuid: string},
        TContext
      > => {
      return useMutation(getAdminCancelReminderMutationOptions(options), queryClient);
    }
    export type adminListLeadSourcesResponse200 = {
  data: SourceOut[]
  status: 200
}

export type adminListLeadSourcesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListLeadSourcesResponseSuccess = (adminListLeadSourcesResponse200) & {
  headers: Headers;
};
export type adminListLeadSourcesResponseError = (adminListLeadSourcesResponse422) & {
  headers: Headers;
};

export type adminListLeadSourcesResponse = (adminListLeadSourcesResponseSuccess | adminListLeadSourcesResponseError)

export const getAdminListLeadSourcesUrl = (params?: AdminListLeadSourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/crm/sources?${stringifiedParams}` : `/api/v1/admin/crm/sources`
}

/**
 * @summary List Sources
 */
export const adminListLeadSources = async (params?: AdminListLeadSourcesParams, options?: RequestInit): Promise<adminListLeadSourcesResponse> => {

  return mutator<adminListLeadSourcesResponse>(getAdminListLeadSourcesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListLeadSourcesQueryKey = (params?: AdminListLeadSourcesParams,) => {
    return [
    `/api/v1/admin/crm/sources`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListLeadSourcesQueryOptions = <TData = Awaited<ReturnType<typeof adminListLeadSources>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListLeadSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadSources>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListLeadSourcesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListLeadSources>>> = ({ signal }) => adminListLeadSources(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListLeadSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListLeadSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListLeadSources>>>
export type AdminListLeadSourcesQueryError = ErrorType<HTTPValidationError>


export function useAdminListLeadSources<TData = Awaited<ReturnType<typeof adminListLeadSources>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListLeadSourcesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadSources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeadSources>>,
          TError,
          Awaited<ReturnType<typeof adminListLeadSources>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeadSources<TData = Awaited<ReturnType<typeof adminListLeadSources>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListLeadSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadSources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListLeadSources>>,
          TError,
          Awaited<ReturnType<typeof adminListLeadSources>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListLeadSources<TData = Awaited<ReturnType<typeof adminListLeadSources>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListLeadSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadSources>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sources
 */

export function useAdminListLeadSources<TData = Awaited<ReturnType<typeof adminListLeadSources>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListLeadSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListLeadSources>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListLeadSourcesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateLeadSourceResponse201 = {
  data: SourceOut
  status: 201
}

export type adminCreateLeadSourceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateLeadSourceResponseSuccess = (adminCreateLeadSourceResponse201) & {
  headers: Headers;
};
export type adminCreateLeadSourceResponseError = (adminCreateLeadSourceResponse422) & {
  headers: Headers;
};

export type adminCreateLeadSourceResponse = (adminCreateLeadSourceResponseSuccess | adminCreateLeadSourceResponseError)

export const getAdminCreateLeadSourceUrl = () => {




  return `/api/v1/admin/crm/sources`
}

/**
 * @summary Create Source
 */
export const adminCreateLeadSource = async (sourceCreate: SourceCreate, options?: RequestInit): Promise<adminCreateLeadSourceResponse> => {

  return mutator<adminCreateLeadSourceResponse>(getAdminCreateLeadSourceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sourceCreate)
  }
);}




export const getAdminCreateLeadSourceMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateLeadSource>>, TError,{data: BodyType<SourceCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateLeadSource>>, TError,{data: BodyType<SourceCreate>}, TContext> => {

const mutationKey = ['adminCreateLeadSource'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateLeadSource>>, {data: BodyType<SourceCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateLeadSource(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateLeadSourceMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateLeadSource>>>
    export type AdminCreateLeadSourceMutationBody = BodyType<SourceCreate>
    export type AdminCreateLeadSourceMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Source
 */
export const useAdminCreateLeadSource = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateLeadSource>>, TError,{data: BodyType<SourceCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateLeadSource>>,
        TError,
        {data: BodyType<SourceCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateLeadSourceMutationOptions(options), queryClient);
    }
    export type adminUpdateLeadSourceResponse200 = {
  data: SourceOut
  status: 200
}

export type adminUpdateLeadSourceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateLeadSourceResponseSuccess = (adminUpdateLeadSourceResponse200) & {
  headers: Headers;
};
export type adminUpdateLeadSourceResponseError = (adminUpdateLeadSourceResponse422) & {
  headers: Headers;
};

export type adminUpdateLeadSourceResponse = (adminUpdateLeadSourceResponseSuccess | adminUpdateLeadSourceResponseError)

export const getAdminUpdateLeadSourceUrl = (sourceUuid: string,) => {




  return `/api/v1/admin/crm/sources/${sourceUuid}`
}

/**
 * @summary Update Source
 */
export const adminUpdateLeadSource = async (sourceUuid: string,
    sourceUpdate: SourceUpdate, options?: RequestInit): Promise<adminUpdateLeadSourceResponse> => {

  return mutator<adminUpdateLeadSourceResponse>(getAdminUpdateLeadSourceUrl(sourceUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sourceUpdate)
  }
);}




export const getAdminUpdateLeadSourceMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLeadSource>>, TError,{sourceUuid: string;data: BodyType<SourceUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLeadSource>>, TError,{sourceUuid: string;data: BodyType<SourceUpdate>}, TContext> => {

const mutationKey = ['adminUpdateLeadSource'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateLeadSource>>, {sourceUuid: string;data: BodyType<SourceUpdate>}> = (props) => {
          const {sourceUuid,data} = props ?? {};

          return  adminUpdateLeadSource(sourceUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateLeadSourceMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateLeadSource>>>
    export type AdminUpdateLeadSourceMutationBody = BodyType<SourceUpdate>
    export type AdminUpdateLeadSourceMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Source
 */
export const useAdminUpdateLeadSource = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateLeadSource>>, TError,{sourceUuid: string;data: BodyType<SourceUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateLeadSource>>,
        TError,
        {sourceUuid: string;data: BodyType<SourceUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateLeadSourceMutationOptions(options), queryClient);
    }
    export type adminListClosureReasonsResponse200 = {
  data: ClosureReasonOut[]
  status: 200
}

export type adminListClosureReasonsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListClosureReasonsResponseSuccess = (adminListClosureReasonsResponse200) & {
  headers: Headers;
};
export type adminListClosureReasonsResponseError = (adminListClosureReasonsResponse422) & {
  headers: Headers;
};

export type adminListClosureReasonsResponse = (adminListClosureReasonsResponseSuccess | adminListClosureReasonsResponseError)

export const getAdminListClosureReasonsUrl = (params?: AdminListClosureReasonsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/crm/closure-reasons?${stringifiedParams}` : `/api/v1/admin/crm/closure-reasons`
}

/**
 * @summary List Closure Reasons
 */
export const adminListClosureReasons = async (params?: AdminListClosureReasonsParams, options?: RequestInit): Promise<adminListClosureReasonsResponse> => {

  return mutator<adminListClosureReasonsResponse>(getAdminListClosureReasonsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListClosureReasonsQueryKey = (params?: AdminListClosureReasonsParams,) => {
    return [
    `/api/v1/admin/crm/closure-reasons`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListClosureReasonsQueryOptions = <TData = Awaited<ReturnType<typeof adminListClosureReasons>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListClosureReasonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListClosureReasons>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListClosureReasonsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListClosureReasons>>> = ({ signal }) => adminListClosureReasons(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListClosureReasons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListClosureReasonsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListClosureReasons>>>
export type AdminListClosureReasonsQueryError = ErrorType<HTTPValidationError>


export function useAdminListClosureReasons<TData = Awaited<ReturnType<typeof adminListClosureReasons>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListClosureReasonsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListClosureReasons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListClosureReasons>>,
          TError,
          Awaited<ReturnType<typeof adminListClosureReasons>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListClosureReasons<TData = Awaited<ReturnType<typeof adminListClosureReasons>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListClosureReasonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListClosureReasons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListClosureReasons>>,
          TError,
          Awaited<ReturnType<typeof adminListClosureReasons>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListClosureReasons<TData = Awaited<ReturnType<typeof adminListClosureReasons>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListClosureReasonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListClosureReasons>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Closure Reasons
 */

export function useAdminListClosureReasons<TData = Awaited<ReturnType<typeof adminListClosureReasons>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListClosureReasonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListClosureReasons>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListClosureReasonsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateClosureReasonResponse201 = {
  data: ClosureReasonOut
  status: 201
}

export type adminCreateClosureReasonResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateClosureReasonResponseSuccess = (adminCreateClosureReasonResponse201) & {
  headers: Headers;
};
export type adminCreateClosureReasonResponseError = (adminCreateClosureReasonResponse422) & {
  headers: Headers;
};

export type adminCreateClosureReasonResponse = (adminCreateClosureReasonResponseSuccess | adminCreateClosureReasonResponseError)

export const getAdminCreateClosureReasonUrl = () => {




  return `/api/v1/admin/crm/closure-reasons`
}

/**
 * @summary Create Closure Reason
 */
export const adminCreateClosureReason = async (closureReasonCreate: ClosureReasonCreate, options?: RequestInit): Promise<adminCreateClosureReasonResponse> => {

  return mutator<adminCreateClosureReasonResponse>(getAdminCreateClosureReasonUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(closureReasonCreate)
  }
);}




export const getAdminCreateClosureReasonMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateClosureReason>>, TError,{data: BodyType<ClosureReasonCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateClosureReason>>, TError,{data: BodyType<ClosureReasonCreate>}, TContext> => {

const mutationKey = ['adminCreateClosureReason'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateClosureReason>>, {data: BodyType<ClosureReasonCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateClosureReason(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateClosureReasonMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateClosureReason>>>
    export type AdminCreateClosureReasonMutationBody = BodyType<ClosureReasonCreate>
    export type AdminCreateClosureReasonMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Closure Reason
 */
export const useAdminCreateClosureReason = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateClosureReason>>, TError,{data: BodyType<ClosureReasonCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateClosureReason>>,
        TError,
        {data: BodyType<ClosureReasonCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateClosureReasonMutationOptions(options), queryClient);
    }
    export type adminUpdateClosureReasonResponse200 = {
  data: ClosureReasonOut
  status: 200
}

export type adminUpdateClosureReasonResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateClosureReasonResponseSuccess = (adminUpdateClosureReasonResponse200) & {
  headers: Headers;
};
export type adminUpdateClosureReasonResponseError = (adminUpdateClosureReasonResponse422) & {
  headers: Headers;
};

export type adminUpdateClosureReasonResponse = (adminUpdateClosureReasonResponseSuccess | adminUpdateClosureReasonResponseError)

export const getAdminUpdateClosureReasonUrl = (reasonUuid: string,) => {




  return `/api/v1/admin/crm/closure-reasons/${reasonUuid}`
}

/**
 * @summary Update Closure Reason
 */
export const adminUpdateClosureReason = async (reasonUuid: string,
    closureReasonUpdate: ClosureReasonUpdate, options?: RequestInit): Promise<adminUpdateClosureReasonResponse> => {

  return mutator<adminUpdateClosureReasonResponse>(getAdminUpdateClosureReasonUrl(reasonUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(closureReasonUpdate)
  }
);}




export const getAdminUpdateClosureReasonMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateClosureReason>>, TError,{reasonUuid: string;data: BodyType<ClosureReasonUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateClosureReason>>, TError,{reasonUuid: string;data: BodyType<ClosureReasonUpdate>}, TContext> => {

const mutationKey = ['adminUpdateClosureReason'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateClosureReason>>, {reasonUuid: string;data: BodyType<ClosureReasonUpdate>}> = (props) => {
          const {reasonUuid,data} = props ?? {};

          return  adminUpdateClosureReason(reasonUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateClosureReasonMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateClosureReason>>>
    export type AdminUpdateClosureReasonMutationBody = BodyType<ClosureReasonUpdate>
    export type AdminUpdateClosureReasonMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Closure Reason
 */
export const useAdminUpdateClosureReason = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateClosureReason>>, TError,{reasonUuid: string;data: BodyType<ClosureReasonUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateClosureReason>>,
        TError,
        {reasonUuid: string;data: BodyType<ClosureReasonUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateClosureReasonMutationOptions(options), queryClient);
    }
