/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminListManufacturingOrdersParams,
  AdminPreviewManufacturingOrderParams,
  HTTPValidationError,
  ManufacturingComplete,
  ManufacturingCreate,
  ManufacturingDetail,
  ManufacturingList,
  ManufacturingPreview,
  ManufacturingUpdate
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListManufacturingOrdersResponse200 = {
  data: ManufacturingList
  status: 200
}

export type adminListManufacturingOrdersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListManufacturingOrdersResponseSuccess = (adminListManufacturingOrdersResponse200) & {
  headers: Headers;
};
export type adminListManufacturingOrdersResponseError = (adminListManufacturingOrdersResponse422) & {
  headers: Headers;
};

export type adminListManufacturingOrdersResponse = (adminListManufacturingOrdersResponseSuccess | adminListManufacturingOrdersResponseError)

export const getAdminListManufacturingOrdersUrl = (params?: AdminListManufacturingOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/manufacturing/orders?${stringifiedParams}` : `/api/v1/admin/manufacturing/orders`
}

/**
 * @summary List Manufacturing Orders
 */
export const adminListManufacturingOrders = async (params?: AdminListManufacturingOrdersParams, options?: RequestInit): Promise<adminListManufacturingOrdersResponse> => {

  return mutator<adminListManufacturingOrdersResponse>(getAdminListManufacturingOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListManufacturingOrdersQueryKey = (params?: AdminListManufacturingOrdersParams,) => {
    return [
    `/api/v1/admin/manufacturing/orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListManufacturingOrdersQueryOptions = <TData = Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListManufacturingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListManufacturingOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListManufacturingOrders>>> = ({ signal }) => adminListManufacturingOrders(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListManufacturingOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListManufacturingOrders>>>
export type AdminListManufacturingOrdersQueryError = ErrorType<HTTPValidationError>


export function useAdminListManufacturingOrders<TData = Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListManufacturingOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListManufacturingOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListManufacturingOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListManufacturingOrders<TData = Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListManufacturingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListManufacturingOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListManufacturingOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListManufacturingOrders<TData = Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListManufacturingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Manufacturing Orders
 */

export function useAdminListManufacturingOrders<TData = Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListManufacturingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListManufacturingOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListManufacturingOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateManufacturingOrderResponse201 = {
  data: ManufacturingDetail
  status: 201
}

export type adminCreateManufacturingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateManufacturingOrderResponseSuccess = (adminCreateManufacturingOrderResponse201) & {
  headers: Headers;
};
export type adminCreateManufacturingOrderResponseError = (adminCreateManufacturingOrderResponse422) & {
  headers: Headers;
};

export type adminCreateManufacturingOrderResponse = (adminCreateManufacturingOrderResponseSuccess | adminCreateManufacturingOrderResponseError)

export const getAdminCreateManufacturingOrderUrl = () => {




  return `/api/v1/admin/manufacturing/orders`
}

/**
 * @summary Create Manufacturing Order
 */
export const adminCreateManufacturingOrder = async (manufacturingCreate: ManufacturingCreate, options?: RequestInit): Promise<adminCreateManufacturingOrderResponse> => {

  return mutator<adminCreateManufacturingOrderResponse>(getAdminCreateManufacturingOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(manufacturingCreate)
  }
);}




export const getAdminCreateManufacturingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateManufacturingOrder>>, TError,{data: BodyType<ManufacturingCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateManufacturingOrder>>, TError,{data: BodyType<ManufacturingCreate>}, TContext> => {

const mutationKey = ['adminCreateManufacturingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateManufacturingOrder>>, {data: BodyType<ManufacturingCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateManufacturingOrder(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateManufacturingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateManufacturingOrder>>>
    export type AdminCreateManufacturingOrderMutationBody = BodyType<ManufacturingCreate>
    export type AdminCreateManufacturingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Manufacturing Order
 */
export const useAdminCreateManufacturingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateManufacturingOrder>>, TError,{data: BodyType<ManufacturingCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateManufacturingOrder>>,
        TError,
        {data: BodyType<ManufacturingCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateManufacturingOrderMutationOptions(options), queryClient);
    }
    export type adminGetManufacturingOrderResponse200 = {
  data: ManufacturingDetail
  status: 200
}

export type adminGetManufacturingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetManufacturingOrderResponseSuccess = (adminGetManufacturingOrderResponse200) & {
  headers: Headers;
};
export type adminGetManufacturingOrderResponseError = (adminGetManufacturingOrderResponse422) & {
  headers: Headers;
};

export type adminGetManufacturingOrderResponse = (adminGetManufacturingOrderResponseSuccess | adminGetManufacturingOrderResponseError)

export const getAdminGetManufacturingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/manufacturing/orders/${orderId}`
}

/**
 * @summary Get Manufacturing Order
 */
export const adminGetManufacturingOrder = async (orderId: number, options?: RequestInit): Promise<adminGetManufacturingOrderResponse> => {

  return mutator<adminGetManufacturingOrderResponse>(getAdminGetManufacturingOrderUrl(orderId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetManufacturingOrderQueryKey = (orderId: number,) => {
    return [
    `/api/v1/admin/manufacturing/orders/${orderId}`
    ] as const;
    }


export const getAdminGetManufacturingOrderQueryOptions = <TData = Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetManufacturingOrderQueryKey(orderId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetManufacturingOrder>>> = ({ signal }) => adminGetManufacturingOrder(orderId, { signal });





   return  { queryKey, queryFn, enabled: orderId !== null && orderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetManufacturingOrderQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetManufacturingOrder>>>
export type AdminGetManufacturingOrderQueryError = ErrorType<HTTPValidationError>


export function useAdminGetManufacturingOrder<TData = Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetManufacturingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetManufacturingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetManufacturingOrder<TData = Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetManufacturingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetManufacturingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetManufacturingOrder<TData = Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Manufacturing Order
 */

export function useAdminGetManufacturingOrder<TData = Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetManufacturingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetManufacturingOrderQueryOptions(orderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdateManufacturingOrderResponse200 = {
  data: ManufacturingDetail
  status: 200
}

export type adminUpdateManufacturingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateManufacturingOrderResponseSuccess = (adminUpdateManufacturingOrderResponse200) & {
  headers: Headers;
};
export type adminUpdateManufacturingOrderResponseError = (adminUpdateManufacturingOrderResponse422) & {
  headers: Headers;
};

export type adminUpdateManufacturingOrderResponse = (adminUpdateManufacturingOrderResponseSuccess | adminUpdateManufacturingOrderResponseError)

export const getAdminUpdateManufacturingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/manufacturing/orders/${orderId}`
}

/**
 * @summary Update Manufacturing Order
 */
export const adminUpdateManufacturingOrder = async (orderId: number,
    manufacturingUpdate: ManufacturingUpdate, options?: RequestInit): Promise<adminUpdateManufacturingOrderResponse> => {

  return mutator<adminUpdateManufacturingOrderResponse>(getAdminUpdateManufacturingOrderUrl(orderId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(manufacturingUpdate)
  }
);}




export const getAdminUpdateManufacturingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateManufacturingOrder>>, TError,{orderId: number;data: BodyType<ManufacturingUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateManufacturingOrder>>, TError,{orderId: number;data: BodyType<ManufacturingUpdate>}, TContext> => {

const mutationKey = ['adminUpdateManufacturingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateManufacturingOrder>>, {orderId: number;data: BodyType<ManufacturingUpdate>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  adminUpdateManufacturingOrder(orderId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateManufacturingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateManufacturingOrder>>>
    export type AdminUpdateManufacturingOrderMutationBody = BodyType<ManufacturingUpdate>
    export type AdminUpdateManufacturingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Manufacturing Order
 */
export const useAdminUpdateManufacturingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateManufacturingOrder>>, TError,{orderId: number;data: BodyType<ManufacturingUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateManufacturingOrder>>,
        TError,
        {orderId: number;data: BodyType<ManufacturingUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateManufacturingOrderMutationOptions(options), queryClient);
    }
    export type adminPreviewManufacturingOrderResponse200 = {
  data: ManufacturingPreview
  status: 200
}

export type adminPreviewManufacturingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminPreviewManufacturingOrderResponseSuccess = (adminPreviewManufacturingOrderResponse200) & {
  headers: Headers;
};
export type adminPreviewManufacturingOrderResponseError = (adminPreviewManufacturingOrderResponse422) & {
  headers: Headers;
};

export type adminPreviewManufacturingOrderResponse = (adminPreviewManufacturingOrderResponseSuccess | adminPreviewManufacturingOrderResponseError)

export const getAdminPreviewManufacturingOrderUrl = (orderId: number,
    params?: AdminPreviewManufacturingOrderParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/manufacturing/orders/${orderId}/preview?${stringifiedParams}` : `/api/v1/admin/manufacturing/orders/${orderId}/preview`
}

/**
 * @summary Preview Manufacturing Order
 */
export const adminPreviewManufacturingOrder = async (orderId: number,
    params?: AdminPreviewManufacturingOrderParams, options?: RequestInit): Promise<adminPreviewManufacturingOrderResponse> => {

  return mutator<adminPreviewManufacturingOrderResponse>(getAdminPreviewManufacturingOrderUrl(orderId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminPreviewManufacturingOrderQueryKey = (orderId: number,
    params?: AdminPreviewManufacturingOrderParams,) => {
    return [
    `/api/v1/admin/manufacturing/orders/${orderId}/preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminPreviewManufacturingOrderQueryOptions = <TData = Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(orderId: number,
    params?: AdminPreviewManufacturingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminPreviewManufacturingOrderQueryKey(orderId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>> = ({ signal }) => adminPreviewManufacturingOrder(orderId,params, { signal });





   return  { queryKey, queryFn, enabled: orderId !== null && orderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminPreviewManufacturingOrderQueryResult = NonNullable<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>>
export type AdminPreviewManufacturingOrderQueryError = ErrorType<HTTPValidationError>


export function useAdminPreviewManufacturingOrder<TData = Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params: undefined |  AdminPreviewManufacturingOrderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPreviewManufacturingOrder<TData = Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params?: AdminPreviewManufacturingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPreviewManufacturingOrder<TData = Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params?: AdminPreviewManufacturingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview Manufacturing Order
 */

export function useAdminPreviewManufacturingOrder<TData = Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params?: AdminPreviewManufacturingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewManufacturingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminPreviewManufacturingOrderQueryOptions(orderId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCompleteManufacturingOrderResponse200 = {
  data: ManufacturingDetail
  status: 200
}

export type adminCompleteManufacturingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCompleteManufacturingOrderResponseSuccess = (adminCompleteManufacturingOrderResponse200) & {
  headers: Headers;
};
export type adminCompleteManufacturingOrderResponseError = (adminCompleteManufacturingOrderResponse422) & {
  headers: Headers;
};

export type adminCompleteManufacturingOrderResponse = (adminCompleteManufacturingOrderResponseSuccess | adminCompleteManufacturingOrderResponseError)

export const getAdminCompleteManufacturingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/manufacturing/orders/${orderId}/complete`
}

/**
 * @summary Complete Manufacturing Order
 */
export const adminCompleteManufacturingOrder = async (orderId: number,
    manufacturingComplete: ManufacturingComplete, options?: RequestInit): Promise<adminCompleteManufacturingOrderResponse> => {

  return mutator<adminCompleteManufacturingOrderResponse>(getAdminCompleteManufacturingOrderUrl(orderId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(manufacturingComplete)
  }
);}




export const getAdminCompleteManufacturingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteManufacturingOrder>>, TError,{orderId: number;data: BodyType<ManufacturingComplete>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCompleteManufacturingOrder>>, TError,{orderId: number;data: BodyType<ManufacturingComplete>}, TContext> => {

const mutationKey = ['adminCompleteManufacturingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCompleteManufacturingOrder>>, {orderId: number;data: BodyType<ManufacturingComplete>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  adminCompleteManufacturingOrder(orderId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCompleteManufacturingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCompleteManufacturingOrder>>>
    export type AdminCompleteManufacturingOrderMutationBody = BodyType<ManufacturingComplete>
    export type AdminCompleteManufacturingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Complete Manufacturing Order
 */
export const useAdminCompleteManufacturingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteManufacturingOrder>>, TError,{orderId: number;data: BodyType<ManufacturingComplete>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCompleteManufacturingOrder>>,
        TError,
        {orderId: number;data: BodyType<ManufacturingComplete>},
        TContext
      > => {
      return useMutation(getAdminCompleteManufacturingOrderMutationOptions(options), queryClient);
    }
    export type adminCancelManufacturingOrderResponse200 = {
  data: ManufacturingDetail
  status: 200
}

export type adminCancelManufacturingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCancelManufacturingOrderResponseSuccess = (adminCancelManufacturingOrderResponse200) & {
  headers: Headers;
};
export type adminCancelManufacturingOrderResponseError = (adminCancelManufacturingOrderResponse422) & {
  headers: Headers;
};

export type adminCancelManufacturingOrderResponse = (adminCancelManufacturingOrderResponseSuccess | adminCancelManufacturingOrderResponseError)

export const getAdminCancelManufacturingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/manufacturing/orders/${orderId}/cancel`
}

/**
 * @summary Cancel Manufacturing Order
 */
export const adminCancelManufacturingOrder = async (orderId: number, options?: RequestInit): Promise<adminCancelManufacturingOrderResponse> => {

  return mutator<adminCancelManufacturingOrderResponse>(getAdminCancelManufacturingOrderUrl(orderId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminCancelManufacturingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelManufacturingOrder>>, TError,{orderId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCancelManufacturingOrder>>, TError,{orderId: number}, TContext> => {

const mutationKey = ['adminCancelManufacturingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCancelManufacturingOrder>>, {orderId: number}> = (props) => {
          const {orderId} = props ?? {};

          return  adminCancelManufacturingOrder(orderId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCancelManufacturingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCancelManufacturingOrder>>>

    export type AdminCancelManufacturingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Cancel Manufacturing Order
 */
export const useAdminCancelManufacturingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelManufacturingOrder>>, TError,{orderId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCancelManufacturingOrder>>,
        TError,
        {orderId: number},
        TContext
      > => {
      return useMutation(getAdminCancelManufacturingOrderMutationOptions(options), queryClient);
    }
