/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminListMediaParams,
  CreateUploadRequest,
  DownloadUrlResponse,
  HTTPValidationError,
  MediaItem,
  MediaListResponse,
  PresignedUploadResponse
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminCreateMediaUploadResponse201 = {
  data: PresignedUploadResponse
  status: 201
}

export type adminCreateMediaUploadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateMediaUploadResponseSuccess = (adminCreateMediaUploadResponse201) & {
  headers: Headers;
};
export type adminCreateMediaUploadResponseError = (adminCreateMediaUploadResponse422) & {
  headers: Headers;
};

export type adminCreateMediaUploadResponse = (adminCreateMediaUploadResponseSuccess | adminCreateMediaUploadResponseError)

export const getAdminCreateMediaUploadUrl = () => {




  return `/api/v1/admin/media/uploads`
}

/**
 * @summary Create Upload
 */
export const adminCreateMediaUpload = async (createUploadRequest: CreateUploadRequest, options?: RequestInit): Promise<adminCreateMediaUploadResponse> => {

  return mutator<adminCreateMediaUploadResponse>(getAdminCreateMediaUploadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUploadRequest)
  }
);}




export const getAdminCreateMediaUploadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateMediaUpload>>, TError,{data: BodyType<CreateUploadRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateMediaUpload>>, TError,{data: BodyType<CreateUploadRequest>}, TContext> => {

const mutationKey = ['adminCreateMediaUpload'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateMediaUpload>>, {data: BodyType<CreateUploadRequest>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateMediaUpload(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateMediaUploadMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateMediaUpload>>>
    export type AdminCreateMediaUploadMutationBody = BodyType<CreateUploadRequest>
    export type AdminCreateMediaUploadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Upload
 */
export const useAdminCreateMediaUpload = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateMediaUpload>>, TError,{data: BodyType<CreateUploadRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateMediaUpload>>,
        TError,
        {data: BodyType<CreateUploadRequest>},
        TContext
      > => {
      return useMutation(getAdminCreateMediaUploadMutationOptions(options), queryClient);
    }
    export type adminConfirmMediaUploadResponse200 = {
  data: MediaItem
  status: 200
}

export type adminConfirmMediaUploadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminConfirmMediaUploadResponseSuccess = (adminConfirmMediaUploadResponse200) & {
  headers: Headers;
};
export type adminConfirmMediaUploadResponseError = (adminConfirmMediaUploadResponse422) & {
  headers: Headers;
};

export type adminConfirmMediaUploadResponse = (adminConfirmMediaUploadResponseSuccess | adminConfirmMediaUploadResponseError)

export const getAdminConfirmMediaUploadUrl = (mediaUuid: string,) => {




  return `/api/v1/admin/media/uploads/${mediaUuid}/confirm`
}

/**
 * @summary Confirm Upload
 */
export const adminConfirmMediaUpload = async (mediaUuid: string, options?: RequestInit): Promise<adminConfirmMediaUploadResponse> => {

  return mutator<adminConfirmMediaUploadResponse>(getAdminConfirmMediaUploadUrl(mediaUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminConfirmMediaUploadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminConfirmMediaUpload>>, TError,{mediaUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminConfirmMediaUpload>>, TError,{mediaUuid: string}, TContext> => {

const mutationKey = ['adminConfirmMediaUpload'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminConfirmMediaUpload>>, {mediaUuid: string}> = (props) => {
          const {mediaUuid} = props ?? {};

          return  adminConfirmMediaUpload(mediaUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminConfirmMediaUploadMutationResult = NonNullable<Awaited<ReturnType<typeof adminConfirmMediaUpload>>>

    export type AdminConfirmMediaUploadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Confirm Upload
 */
export const useAdminConfirmMediaUpload = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminConfirmMediaUpload>>, TError,{mediaUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminConfirmMediaUpload>>,
        TError,
        {mediaUuid: string},
        TContext
      > => {
      return useMutation(getAdminConfirmMediaUploadMutationOptions(options), queryClient);
    }
    export type adminListMediaResponse200 = {
  data: MediaListResponse
  status: 200
}

export type adminListMediaResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListMediaResponseSuccess = (adminListMediaResponse200) & {
  headers: Headers;
};
export type adminListMediaResponseError = (adminListMediaResponse422) & {
  headers: Headers;
};

export type adminListMediaResponse = (adminListMediaResponseSuccess | adminListMediaResponseError)

export const getAdminListMediaUrl = (params: AdminListMediaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/media?${stringifiedParams}` : `/api/v1/admin/media`
}

/**
 * @summary List Media
 */
export const adminListMedia = async (params: AdminListMediaParams, options?: RequestInit): Promise<adminListMediaResponse> => {

  return mutator<adminListMediaResponse>(getAdminListMediaUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListMediaQueryKey = (params?: AdminListMediaParams,) => {
    return [
    `/api/v1/admin/media`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListMediaQueryOptions = <TData = Awaited<ReturnType<typeof adminListMedia>>, TError = ErrorType<HTTPValidationError>>(params: AdminListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMedia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListMediaQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListMedia>>> = ({ signal }) => adminListMedia(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListMediaQueryResult = NonNullable<Awaited<ReturnType<typeof adminListMedia>>>
export type AdminListMediaQueryError = ErrorType<HTTPValidationError>


export function useAdminListMedia<TData = Awaited<ReturnType<typeof adminListMedia>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminListMediaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMedia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMedia>>,
          TError,
          Awaited<ReturnType<typeof adminListMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMedia<TData = Awaited<ReturnType<typeof adminListMedia>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMedia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMedia>>,
          TError,
          Awaited<ReturnType<typeof adminListMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMedia<TData = Awaited<ReturnType<typeof adminListMedia>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Media
 */

export function useAdminListMedia<TData = Awaited<ReturnType<typeof adminListMedia>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListMediaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminGetMediaDownloadUrlResponse200 = {
  data: DownloadUrlResponse
  status: 200
}

export type adminGetMediaDownloadUrlResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetMediaDownloadUrlResponseSuccess = (adminGetMediaDownloadUrlResponse200) & {
  headers: Headers;
};
export type adminGetMediaDownloadUrlResponseError = (adminGetMediaDownloadUrlResponse422) & {
  headers: Headers;
};

export type adminGetMediaDownloadUrlResponse = (adminGetMediaDownloadUrlResponseSuccess | adminGetMediaDownloadUrlResponseError)

export const getAdminGetMediaDownloadUrlUrl = (mediaUuid: string,) => {




  return `/api/v1/admin/media/${mediaUuid}/download-url`
}

/**
 * @summary Get Download Url
 */
export const adminGetMediaDownloadUrl = async (mediaUuid: string, options?: RequestInit): Promise<adminGetMediaDownloadUrlResponse> => {

  return mutator<adminGetMediaDownloadUrlResponse>(getAdminGetMediaDownloadUrlUrl(mediaUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetMediaDownloadUrlQueryKey = (mediaUuid: string,) => {
    return [
    `/api/v1/admin/media/${mediaUuid}/download-url`
    ] as const;
    }


export const getAdminGetMediaDownloadUrlQueryOptions = <TData = Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError = ErrorType<HTTPValidationError>>(mediaUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetMediaDownloadUrlQueryKey(mediaUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>> = ({ signal }) => adminGetMediaDownloadUrl(mediaUuid, { signal });





   return  { queryKey, queryFn, enabled: mediaUuid !== null && mediaUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetMediaDownloadUrlQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>>
export type AdminGetMediaDownloadUrlQueryError = ErrorType<HTTPValidationError>


export function useAdminGetMediaDownloadUrl<TData = Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError = ErrorType<HTTPValidationError>>(
 mediaUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetMediaDownloadUrl<TData = Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError = ErrorType<HTTPValidationError>>(
 mediaUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetMediaDownloadUrl<TData = Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError = ErrorType<HTTPValidationError>>(
 mediaUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Download Url
 */

export function useAdminGetMediaDownloadUrl<TData = Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError = ErrorType<HTTPValidationError>>(
 mediaUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetMediaDownloadUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetMediaDownloadUrlQueryOptions(mediaUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminDeleteMediaResponse204 = {
  data: void
  status: 204
}

export type adminDeleteMediaResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteMediaResponseSuccess = (adminDeleteMediaResponse204) & {
  headers: Headers;
};
export type adminDeleteMediaResponseError = (adminDeleteMediaResponse422) & {
  headers: Headers;
};

export type adminDeleteMediaResponse = (adminDeleteMediaResponseSuccess | adminDeleteMediaResponseError)

export const getAdminDeleteMediaUrl = (mediaUuid: string,) => {




  return `/api/v1/admin/media/${mediaUuid}`
}

/**
 * @summary Delete Media
 */
export const adminDeleteMedia = async (mediaUuid: string, options?: RequestInit): Promise<adminDeleteMediaResponse> => {

  return mutator<adminDeleteMediaResponse>(getAdminDeleteMediaUrl(mediaUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeleteMediaMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteMedia>>, TError,{mediaUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteMedia>>, TError,{mediaUuid: string}, TContext> => {

const mutationKey = ['adminDeleteMedia'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteMedia>>, {mediaUuid: string}> = (props) => {
          const {mediaUuid} = props ?? {};

          return  adminDeleteMedia(mediaUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteMediaMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteMedia>>>

    export type AdminDeleteMediaMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Media
 */
export const useAdminDeleteMedia = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteMedia>>, TError,{mediaUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteMedia>>,
        TError,
        {mediaUuid: string},
        TContext
      > => {
      return useMutation(getAdminDeleteMediaMutationOptions(options), queryClient);
    }
