/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminListProcessingOrdersParams,
  AdminPreviewProcessingOrderParams,
  HTTPValidationError,
  ProcessingComplete,
  ProcessingCreate,
  ProcessingDetail,
  ProcessingList,
  ProcessingPreview,
  ProcessingUpdate
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListProcessingOrdersResponse200 = {
  data: ProcessingList
  status: 200
}

export type adminListProcessingOrdersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListProcessingOrdersResponseSuccess = (adminListProcessingOrdersResponse200) & {
  headers: Headers;
};
export type adminListProcessingOrdersResponseError = (adminListProcessingOrdersResponse422) & {
  headers: Headers;
};

export type adminListProcessingOrdersResponse = (adminListProcessingOrdersResponseSuccess | adminListProcessingOrdersResponseError)

export const getAdminListProcessingOrdersUrl = (params?: AdminListProcessingOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/processing/orders?${stringifiedParams}` : `/api/v1/admin/processing/orders`
}

/**
 * @summary List Processing Orders
 */
export const adminListProcessingOrders = async (params?: AdminListProcessingOrdersParams, options?: RequestInit): Promise<adminListProcessingOrdersResponse> => {

  return mutator<adminListProcessingOrdersResponse>(getAdminListProcessingOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListProcessingOrdersQueryKey = (params?: AdminListProcessingOrdersParams,) => {
    return [
    `/api/v1/admin/processing/orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListProcessingOrdersQueryOptions = <TData = Awaited<ReturnType<typeof adminListProcessingOrders>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListProcessingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProcessingOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListProcessingOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListProcessingOrders>>> = ({ signal }) => adminListProcessingOrders(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListProcessingOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListProcessingOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListProcessingOrders>>>
export type AdminListProcessingOrdersQueryError = ErrorType<HTTPValidationError>


export function useAdminListProcessingOrders<TData = Awaited<ReturnType<typeof adminListProcessingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListProcessingOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProcessingOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListProcessingOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListProcessingOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListProcessingOrders<TData = Awaited<ReturnType<typeof adminListProcessingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListProcessingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProcessingOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListProcessingOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListProcessingOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListProcessingOrders<TData = Awaited<ReturnType<typeof adminListProcessingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListProcessingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProcessingOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Processing Orders
 */

export function useAdminListProcessingOrders<TData = Awaited<ReturnType<typeof adminListProcessingOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListProcessingOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProcessingOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListProcessingOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateProcessingOrderResponse201 = {
  data: ProcessingDetail
  status: 201
}

export type adminCreateProcessingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateProcessingOrderResponseSuccess = (adminCreateProcessingOrderResponse201) & {
  headers: Headers;
};
export type adminCreateProcessingOrderResponseError = (adminCreateProcessingOrderResponse422) & {
  headers: Headers;
};

export type adminCreateProcessingOrderResponse = (adminCreateProcessingOrderResponseSuccess | adminCreateProcessingOrderResponseError)

export const getAdminCreateProcessingOrderUrl = () => {




  return `/api/v1/admin/processing/orders`
}

/**
 * @summary Create Processing Order
 */
export const adminCreateProcessingOrder = async (processingCreate: ProcessingCreate, options?: RequestInit): Promise<adminCreateProcessingOrderResponse> => {

  return mutator<adminCreateProcessingOrderResponse>(getAdminCreateProcessingOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(processingCreate)
  }
);}




export const getAdminCreateProcessingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateProcessingOrder>>, TError,{data: BodyType<ProcessingCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateProcessingOrder>>, TError,{data: BodyType<ProcessingCreate>}, TContext> => {

const mutationKey = ['adminCreateProcessingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateProcessingOrder>>, {data: BodyType<ProcessingCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateProcessingOrder(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateProcessingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateProcessingOrder>>>
    export type AdminCreateProcessingOrderMutationBody = BodyType<ProcessingCreate>
    export type AdminCreateProcessingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Processing Order
 */
export const useAdminCreateProcessingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateProcessingOrder>>, TError,{data: BodyType<ProcessingCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateProcessingOrder>>,
        TError,
        {data: BodyType<ProcessingCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateProcessingOrderMutationOptions(options), queryClient);
    }
    export type adminGetProcessingOrderResponse200 = {
  data: ProcessingDetail
  status: 200
}

export type adminGetProcessingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetProcessingOrderResponseSuccess = (adminGetProcessingOrderResponse200) & {
  headers: Headers;
};
export type adminGetProcessingOrderResponseError = (adminGetProcessingOrderResponse422) & {
  headers: Headers;
};

export type adminGetProcessingOrderResponse = (adminGetProcessingOrderResponseSuccess | adminGetProcessingOrderResponseError)

export const getAdminGetProcessingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/processing/orders/${orderId}`
}

/**
 * @summary Get Processing Order
 */
export const adminGetProcessingOrder = async (orderId: number, options?: RequestInit): Promise<adminGetProcessingOrderResponse> => {

  return mutator<adminGetProcessingOrderResponse>(getAdminGetProcessingOrderUrl(orderId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetProcessingOrderQueryKey = (orderId: number,) => {
    return [
    `/api/v1/admin/processing/orders/${orderId}`
    ] as const;
    }


export const getAdminGetProcessingOrderQueryOptions = <TData = Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetProcessingOrderQueryKey(orderId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetProcessingOrder>>> = ({ signal }) => adminGetProcessingOrder(orderId, { signal });





   return  { queryKey, queryFn, enabled: orderId !== null && orderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetProcessingOrderQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetProcessingOrder>>>
export type AdminGetProcessingOrderQueryError = ErrorType<HTTPValidationError>


export function useAdminGetProcessingOrder<TData = Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetProcessingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetProcessingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetProcessingOrder<TData = Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetProcessingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetProcessingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetProcessingOrder<TData = Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Processing Order
 */

export function useAdminGetProcessingOrder<TData = Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProcessingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetProcessingOrderQueryOptions(orderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdateProcessingOrderResponse200 = {
  data: ProcessingDetail
  status: 200
}

export type adminUpdateProcessingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateProcessingOrderResponseSuccess = (adminUpdateProcessingOrderResponse200) & {
  headers: Headers;
};
export type adminUpdateProcessingOrderResponseError = (adminUpdateProcessingOrderResponse422) & {
  headers: Headers;
};

export type adminUpdateProcessingOrderResponse = (adminUpdateProcessingOrderResponseSuccess | adminUpdateProcessingOrderResponseError)

export const getAdminUpdateProcessingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/processing/orders/${orderId}`
}

/**
 * @summary Update Processing Order
 */
export const adminUpdateProcessingOrder = async (orderId: number,
    processingUpdate: ProcessingUpdate, options?: RequestInit): Promise<adminUpdateProcessingOrderResponse> => {

  return mutator<adminUpdateProcessingOrderResponse>(getAdminUpdateProcessingOrderUrl(orderId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(processingUpdate)
  }
);}




export const getAdminUpdateProcessingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateProcessingOrder>>, TError,{orderId: number;data: BodyType<ProcessingUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateProcessingOrder>>, TError,{orderId: number;data: BodyType<ProcessingUpdate>}, TContext> => {

const mutationKey = ['adminUpdateProcessingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateProcessingOrder>>, {orderId: number;data: BodyType<ProcessingUpdate>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  adminUpdateProcessingOrder(orderId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateProcessingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateProcessingOrder>>>
    export type AdminUpdateProcessingOrderMutationBody = BodyType<ProcessingUpdate>
    export type AdminUpdateProcessingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Processing Order
 */
export const useAdminUpdateProcessingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateProcessingOrder>>, TError,{orderId: number;data: BodyType<ProcessingUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateProcessingOrder>>,
        TError,
        {orderId: number;data: BodyType<ProcessingUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateProcessingOrderMutationOptions(options), queryClient);
    }
    export type adminPreviewProcessingOrderResponse200 = {
  data: ProcessingPreview
  status: 200
}

export type adminPreviewProcessingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminPreviewProcessingOrderResponseSuccess = (adminPreviewProcessingOrderResponse200) & {
  headers: Headers;
};
export type adminPreviewProcessingOrderResponseError = (adminPreviewProcessingOrderResponse422) & {
  headers: Headers;
};

export type adminPreviewProcessingOrderResponse = (adminPreviewProcessingOrderResponseSuccess | adminPreviewProcessingOrderResponseError)

export const getAdminPreviewProcessingOrderUrl = (orderId: number,
    params?: AdminPreviewProcessingOrderParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/processing/orders/${orderId}/preview?${stringifiedParams}` : `/api/v1/admin/processing/orders/${orderId}/preview`
}

/**
 * @summary Preview Processing Order
 */
export const adminPreviewProcessingOrder = async (orderId: number,
    params?: AdminPreviewProcessingOrderParams, options?: RequestInit): Promise<adminPreviewProcessingOrderResponse> => {

  return mutator<adminPreviewProcessingOrderResponse>(getAdminPreviewProcessingOrderUrl(orderId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminPreviewProcessingOrderQueryKey = (orderId: number,
    params?: AdminPreviewProcessingOrderParams,) => {
    return [
    `/api/v1/admin/processing/orders/${orderId}/preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminPreviewProcessingOrderQueryOptions = <TData = Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(orderId: number,
    params?: AdminPreviewProcessingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminPreviewProcessingOrderQueryKey(orderId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>> = ({ signal }) => adminPreviewProcessingOrder(orderId,params, { signal });





   return  { queryKey, queryFn, enabled: orderId !== null && orderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminPreviewProcessingOrderQueryResult = NonNullable<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>>
export type AdminPreviewProcessingOrderQueryError = ErrorType<HTTPValidationError>


export function useAdminPreviewProcessingOrder<TData = Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params: undefined |  AdminPreviewProcessingOrderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPreviewProcessingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminPreviewProcessingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPreviewProcessingOrder<TData = Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params?: AdminPreviewProcessingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPreviewProcessingOrder>>,
          TError,
          Awaited<ReturnType<typeof adminPreviewProcessingOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPreviewProcessingOrder<TData = Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params?: AdminPreviewProcessingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview Processing Order
 */

export function useAdminPreviewProcessingOrder<TData = Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderId: number,
    params?: AdminPreviewProcessingOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPreviewProcessingOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminPreviewProcessingOrderQueryOptions(orderId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCompleteProcessingOrderResponse200 = {
  data: ProcessingDetail
  status: 200
}

export type adminCompleteProcessingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCompleteProcessingOrderResponseSuccess = (adminCompleteProcessingOrderResponse200) & {
  headers: Headers;
};
export type adminCompleteProcessingOrderResponseError = (adminCompleteProcessingOrderResponse422) & {
  headers: Headers;
};

export type adminCompleteProcessingOrderResponse = (adminCompleteProcessingOrderResponseSuccess | adminCompleteProcessingOrderResponseError)

export const getAdminCompleteProcessingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/processing/orders/${orderId}/complete`
}

/**
 * @summary Complete Processing Order
 */
export const adminCompleteProcessingOrder = async (orderId: number,
    processingComplete: ProcessingComplete, options?: RequestInit): Promise<adminCompleteProcessingOrderResponse> => {

  return mutator<adminCompleteProcessingOrderResponse>(getAdminCompleteProcessingOrderUrl(orderId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(processingComplete)
  }
);}




export const getAdminCompleteProcessingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteProcessingOrder>>, TError,{orderId: number;data: BodyType<ProcessingComplete>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCompleteProcessingOrder>>, TError,{orderId: number;data: BodyType<ProcessingComplete>}, TContext> => {

const mutationKey = ['adminCompleteProcessingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCompleteProcessingOrder>>, {orderId: number;data: BodyType<ProcessingComplete>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  adminCompleteProcessingOrder(orderId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCompleteProcessingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCompleteProcessingOrder>>>
    export type AdminCompleteProcessingOrderMutationBody = BodyType<ProcessingComplete>
    export type AdminCompleteProcessingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Complete Processing Order
 */
export const useAdminCompleteProcessingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteProcessingOrder>>, TError,{orderId: number;data: BodyType<ProcessingComplete>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCompleteProcessingOrder>>,
        TError,
        {orderId: number;data: BodyType<ProcessingComplete>},
        TContext
      > => {
      return useMutation(getAdminCompleteProcessingOrderMutationOptions(options), queryClient);
    }
    export type adminCancelProcessingOrderResponse200 = {
  data: ProcessingDetail
  status: 200
}

export type adminCancelProcessingOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCancelProcessingOrderResponseSuccess = (adminCancelProcessingOrderResponse200) & {
  headers: Headers;
};
export type adminCancelProcessingOrderResponseError = (adminCancelProcessingOrderResponse422) & {
  headers: Headers;
};

export type adminCancelProcessingOrderResponse = (adminCancelProcessingOrderResponseSuccess | adminCancelProcessingOrderResponseError)

export const getAdminCancelProcessingOrderUrl = (orderId: number,) => {




  return `/api/v1/admin/processing/orders/${orderId}/cancel`
}

/**
 * @summary Cancel Processing Order
 */
export const adminCancelProcessingOrder = async (orderId: number, options?: RequestInit): Promise<adminCancelProcessingOrderResponse> => {

  return mutator<adminCancelProcessingOrderResponse>(getAdminCancelProcessingOrderUrl(orderId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminCancelProcessingOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelProcessingOrder>>, TError,{orderId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCancelProcessingOrder>>, TError,{orderId: number}, TContext> => {

const mutationKey = ['adminCancelProcessingOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCancelProcessingOrder>>, {orderId: number}> = (props) => {
          const {orderId} = props ?? {};

          return  adminCancelProcessingOrder(orderId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCancelProcessingOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCancelProcessingOrder>>>

    export type AdminCancelProcessingOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Cancel Processing Order
 */
export const useAdminCancelProcessingOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelProcessingOrder>>, TError,{orderId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCancelProcessingOrder>>,
        TError,
        {orderId: number},
        TContext
      > => {
      return useMutation(getAdminCancelProcessingOrderMutationOptions(options), queryClient);
    }
