/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminListPermissionsParams,
  AdminListRolesParams,
  HTTPValidationError,
  PermissionList,
  PermissionRefs,
  RoleCreate,
  RoleDetailOut,
  RoleList,
  RoleOut,
  RoleStatusUpdate,
  RoleUpdate
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListRolesResponse200 = {
  data: RoleList
  status: 200
}

export type adminListRolesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListRolesResponseSuccess = (adminListRolesResponse200) & {
  headers: Headers;
};
export type adminListRolesResponseError = (adminListRolesResponse422) & {
  headers: Headers;
};

export type adminListRolesResponse = (adminListRolesResponseSuccess | adminListRolesResponseError)

export const getAdminListRolesUrl = (params?: AdminListRolesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/roles?${stringifiedParams}` : `/api/v1/admin/roles`
}

/**
 * @summary List Roles
 */
export const adminListRoles = async (params?: AdminListRolesParams, options?: RequestInit): Promise<adminListRolesResponse> => {

  return mutator<adminListRolesResponse>(getAdminListRolesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListRolesQueryKey = (params?: AdminListRolesParams,) => {
    return [
    `/api/v1/admin/roles`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListRolesQueryOptions = <TData = Awaited<ReturnType<typeof adminListRoles>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListRoles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListRolesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListRoles>>> = ({ signal }) => adminListRoles(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListRolesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListRoles>>>
export type AdminListRolesQueryError = ErrorType<HTTPValidationError>


export function useAdminListRoles<TData = Awaited<ReturnType<typeof adminListRoles>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListRolesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListRoles>>,
          TError,
          Awaited<ReturnType<typeof adminListRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListRoles<TData = Awaited<ReturnType<typeof adminListRoles>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListRoles>>,
          TError,
          Awaited<ReturnType<typeof adminListRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListRoles<TData = Awaited<ReturnType<typeof adminListRoles>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListRoles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Roles
 */

export function useAdminListRoles<TData = Awaited<ReturnType<typeof adminListRoles>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListRoles>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListRolesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateRoleResponse201 = {
  data: RoleOut
  status: 201
}

export type adminCreateRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateRoleResponseSuccess = (adminCreateRoleResponse201) & {
  headers: Headers;
};
export type adminCreateRoleResponseError = (adminCreateRoleResponse422) & {
  headers: Headers;
};

export type adminCreateRoleResponse = (adminCreateRoleResponseSuccess | adminCreateRoleResponseError)

export const getAdminCreateRoleUrl = () => {




  return `/api/v1/admin/roles`
}

/**
 * @summary Create Role
 */
export const adminCreateRole = async (roleCreate: RoleCreate, options?: RequestInit): Promise<adminCreateRoleResponse> => {

  return mutator<adminCreateRoleResponse>(getAdminCreateRoleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(roleCreate)
  }
);}




export const getAdminCreateRoleMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateRole>>, TError,{data: BodyType<RoleCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateRole>>, TError,{data: BodyType<RoleCreate>}, TContext> => {

const mutationKey = ['adminCreateRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateRole>>, {data: BodyType<RoleCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateRole(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateRole>>>
    export type AdminCreateRoleMutationBody = BodyType<RoleCreate>
    export type AdminCreateRoleMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Role
 */
export const useAdminCreateRole = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateRole>>, TError,{data: BodyType<RoleCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateRole>>,
        TError,
        {data: BodyType<RoleCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateRoleMutationOptions(options), queryClient);
    }
    export type adminGetRoleResponse200 = {
  data: RoleDetailOut
  status: 200
}

export type adminGetRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetRoleResponseSuccess = (adminGetRoleResponse200) & {
  headers: Headers;
};
export type adminGetRoleResponseError = (adminGetRoleResponse422) & {
  headers: Headers;
};

export type adminGetRoleResponse = (adminGetRoleResponseSuccess | adminGetRoleResponseError)

export const getAdminGetRoleUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}`
}

/**
 * @summary Get Role
 */
export const adminGetRole = async (roleId: number, options?: RequestInit): Promise<adminGetRoleResponse> => {

  return mutator<adminGetRoleResponse>(getAdminGetRoleUrl(roleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetRoleQueryKey = (roleId: number,) => {
    return [
    `/api/v1/admin/roles/${roleId}`
    ] as const;
    }


export const getAdminGetRoleQueryOptions = <TData = Awaited<ReturnType<typeof adminGetRole>>, TError = ErrorType<HTTPValidationError>>(roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetRole>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetRoleQueryKey(roleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetRole>>> = ({ signal }) => adminGetRole(roleId, { signal });





   return  { queryKey, queryFn, enabled: roleId !== null && roleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetRole>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetRoleQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetRole>>>
export type AdminGetRoleQueryError = ErrorType<HTTPValidationError>


export function useAdminGetRole<TData = Awaited<ReturnType<typeof adminGetRole>>, TError = ErrorType<HTTPValidationError>>(
 roleId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetRole>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetRole>>,
          TError,
          Awaited<ReturnType<typeof adminGetRole>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetRole<TData = Awaited<ReturnType<typeof adminGetRole>>, TError = ErrorType<HTTPValidationError>>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetRole>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetRole>>,
          TError,
          Awaited<ReturnType<typeof adminGetRole>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetRole<TData = Awaited<ReturnType<typeof adminGetRole>>, TError = ErrorType<HTTPValidationError>>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetRole>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Role
 */

export function useAdminGetRole<TData = Awaited<ReturnType<typeof adminGetRole>>, TError = ErrorType<HTTPValidationError>>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetRole>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetRoleQueryOptions(roleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdateRoleResponse200 = {
  data: RoleOut
  status: 200
}

export type adminUpdateRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateRoleResponseSuccess = (adminUpdateRoleResponse200) & {
  headers: Headers;
};
export type adminUpdateRoleResponseError = (adminUpdateRoleResponse422) & {
  headers: Headers;
};

export type adminUpdateRoleResponse = (adminUpdateRoleResponseSuccess | adminUpdateRoleResponseError)

export const getAdminUpdateRoleUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}`
}

/**
 * @summary Update Role
 */
export const adminUpdateRole = async (roleId: number,
    roleUpdate: RoleUpdate, options?: RequestInit): Promise<adminUpdateRoleResponse> => {

  return mutator<adminUpdateRoleResponse>(getAdminUpdateRoleUrl(roleId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(roleUpdate)
  }
);}




export const getAdminUpdateRoleMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateRole>>, TError,{roleId: number;data: BodyType<RoleUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateRole>>, TError,{roleId: number;data: BodyType<RoleUpdate>}, TContext> => {

const mutationKey = ['adminUpdateRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateRole>>, {roleId: number;data: BodyType<RoleUpdate>}> = (props) => {
          const {roleId,data} = props ?? {};

          return  adminUpdateRole(roleId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateRole>>>
    export type AdminUpdateRoleMutationBody = BodyType<RoleUpdate>
    export type AdminUpdateRoleMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Role
 */
export const useAdminUpdateRole = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateRole>>, TError,{roleId: number;data: BodyType<RoleUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateRole>>,
        TError,
        {roleId: number;data: BodyType<RoleUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateRoleMutationOptions(options), queryClient);
    }
    export type adminDeleteRoleResponse204 = {
  data: void
  status: 204
}

export type adminDeleteRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteRoleResponseSuccess = (adminDeleteRoleResponse204) & {
  headers: Headers;
};
export type adminDeleteRoleResponseError = (adminDeleteRoleResponse422) & {
  headers: Headers;
};

export type adminDeleteRoleResponse = (adminDeleteRoleResponseSuccess | adminDeleteRoleResponseError)

export const getAdminDeleteRoleUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}`
}

/**
 * @summary Delete Role
 */
export const adminDeleteRole = async (roleId: number, options?: RequestInit): Promise<adminDeleteRoleResponse> => {

  return mutator<adminDeleteRoleResponse>(getAdminDeleteRoleUrl(roleId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeleteRoleMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteRole>>, TError,{roleId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteRole>>, TError,{roleId: number}, TContext> => {

const mutationKey = ['adminDeleteRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteRole>>, {roleId: number}> = (props) => {
          const {roleId} = props ?? {};

          return  adminDeleteRole(roleId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteRoleMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteRole>>>

    export type AdminDeleteRoleMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Role
 */
export const useAdminDeleteRole = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteRole>>, TError,{roleId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteRole>>,
        TError,
        {roleId: number},
        TContext
      > => {
      return useMutation(getAdminDeleteRoleMutationOptions(options), queryClient);
    }
    export type adminSetRoleStatusResponse200 = {
  data: RoleOut
  status: 200
}

export type adminSetRoleStatusResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminSetRoleStatusResponseSuccess = (adminSetRoleStatusResponse200) & {
  headers: Headers;
};
export type adminSetRoleStatusResponseError = (adminSetRoleStatusResponse422) & {
  headers: Headers;
};

export type adminSetRoleStatusResponse = (adminSetRoleStatusResponseSuccess | adminSetRoleStatusResponseError)

export const getAdminSetRoleStatusUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}/status`
}

/**
 * @summary Set Role Status
 */
export const adminSetRoleStatus = async (roleId: number,
    roleStatusUpdate: RoleStatusUpdate, options?: RequestInit): Promise<adminSetRoleStatusResponse> => {

  return mutator<adminSetRoleStatusResponse>(getAdminSetRoleStatusUrl(roleId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(roleStatusUpdate)
  }
);}




export const getAdminSetRoleStatusMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminSetRoleStatus>>, TError,{roleId: number;data: BodyType<RoleStatusUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminSetRoleStatus>>, TError,{roleId: number;data: BodyType<RoleStatusUpdate>}, TContext> => {

const mutationKey = ['adminSetRoleStatus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminSetRoleStatus>>, {roleId: number;data: BodyType<RoleStatusUpdate>}> = (props) => {
          const {roleId,data} = props ?? {};

          return  adminSetRoleStatus(roleId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminSetRoleStatusMutationResult = NonNullable<Awaited<ReturnType<typeof adminSetRoleStatus>>>
    export type AdminSetRoleStatusMutationBody = BodyType<RoleStatusUpdate>
    export type AdminSetRoleStatusMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Set Role Status
 */
export const useAdminSetRoleStatus = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminSetRoleStatus>>, TError,{roleId: number;data: BodyType<RoleStatusUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminSetRoleStatus>>,
        TError,
        {roleId: number;data: BodyType<RoleStatusUpdate>},
        TContext
      > => {
      return useMutation(getAdminSetRoleStatusMutationOptions(options), queryClient);
    }
    export type adminGrantPermissionsResponse200 = {
  data: RoleOut
  status: 200
}

export type adminGrantPermissionsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGrantPermissionsResponseSuccess = (adminGrantPermissionsResponse200) & {
  headers: Headers;
};
export type adminGrantPermissionsResponseError = (adminGrantPermissionsResponse422) & {
  headers: Headers;
};

export type adminGrantPermissionsResponse = (adminGrantPermissionsResponseSuccess | adminGrantPermissionsResponseError)

export const getAdminGrantPermissionsUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}/permissions`
}

/**
 * @summary Grant Permissions
 */
export const adminGrantPermissions = async (roleId: number,
    permissionRefs: PermissionRefs, options?: RequestInit): Promise<adminGrantPermissionsResponse> => {

  return mutator<adminGrantPermissionsResponse>(getAdminGrantPermissionsUrl(roleId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(permissionRefs)
  }
);}




export const getAdminGrantPermissionsMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminGrantPermissions>>, TError,{roleId: number;data: BodyType<PermissionRefs>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminGrantPermissions>>, TError,{roleId: number;data: BodyType<PermissionRefs>}, TContext> => {

const mutationKey = ['adminGrantPermissions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminGrantPermissions>>, {roleId: number;data: BodyType<PermissionRefs>}> = (props) => {
          const {roleId,data} = props ?? {};

          return  adminGrantPermissions(roleId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminGrantPermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof adminGrantPermissions>>>
    export type AdminGrantPermissionsMutationBody = BodyType<PermissionRefs>
    export type AdminGrantPermissionsMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Grant Permissions
 */
export const useAdminGrantPermissions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminGrantPermissions>>, TError,{roleId: number;data: BodyType<PermissionRefs>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminGrantPermissions>>,
        TError,
        {roleId: number;data: BodyType<PermissionRefs>},
        TContext
      > => {
      return useMutation(getAdminGrantPermissionsMutationOptions(options), queryClient);
    }
    export type adminRevokePermissionsResponse200 = {
  data: RoleOut
  status: 200
}

export type adminRevokePermissionsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminRevokePermissionsResponseSuccess = (adminRevokePermissionsResponse200) & {
  headers: Headers;
};
export type adminRevokePermissionsResponseError = (adminRevokePermissionsResponse422) & {
  headers: Headers;
};

export type adminRevokePermissionsResponse = (adminRevokePermissionsResponseSuccess | adminRevokePermissionsResponseError)

export const getAdminRevokePermissionsUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}/permissions`
}

/**
 * @summary Revoke Permissions
 */
export const adminRevokePermissions = async (roleId: number,
    permissionRefs: PermissionRefs, options?: RequestInit): Promise<adminRevokePermissionsResponse> => {

  return mutator<adminRevokePermissionsResponse>(getAdminRevokePermissionsUrl(roleId),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(permissionRefs)
  }
);}




export const getAdminRevokePermissionsMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRevokePermissions>>, TError,{roleId: number;data: BodyType<PermissionRefs>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminRevokePermissions>>, TError,{roleId: number;data: BodyType<PermissionRefs>}, TContext> => {

const mutationKey = ['adminRevokePermissions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminRevokePermissions>>, {roleId: number;data: BodyType<PermissionRefs>}> = (props) => {
          const {roleId,data} = props ?? {};

          return  adminRevokePermissions(roleId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminRevokePermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof adminRevokePermissions>>>
    export type AdminRevokePermissionsMutationBody = BodyType<PermissionRefs>
    export type AdminRevokePermissionsMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Revoke Permissions
 */
export const useAdminRevokePermissions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRevokePermissions>>, TError,{roleId: number;data: BodyType<PermissionRefs>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminRevokePermissions>>,
        TError,
        {roleId: number;data: BodyType<PermissionRefs>},
        TContext
      > => {
      return useMutation(getAdminRevokePermissionsMutationOptions(options), queryClient);
    }
    export type adminListPermissionsResponse200 = {
  data: PermissionList
  status: 200
}

export type adminListPermissionsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListPermissionsResponseSuccess = (adminListPermissionsResponse200) & {
  headers: Headers;
};
export type adminListPermissionsResponseError = (adminListPermissionsResponse422) & {
  headers: Headers;
};

export type adminListPermissionsResponse = (adminListPermissionsResponseSuccess | adminListPermissionsResponseError)

export const getAdminListPermissionsUrl = (params?: AdminListPermissionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/permissions?${stringifiedParams}` : `/api/v1/admin/permissions`
}

/**
 * @summary List Permissions
 */
export const adminListPermissions = async (params?: AdminListPermissionsParams, options?: RequestInit): Promise<adminListPermissionsResponse> => {

  return mutator<adminListPermissionsResponse>(getAdminListPermissionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListPermissionsQueryKey = (params?: AdminListPermissionsParams,) => {
    return [
    `/api/v1/admin/permissions`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListPermissionsQueryOptions = <TData = Awaited<ReturnType<typeof adminListPermissions>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPermissions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListPermissionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListPermissions>>> = ({ signal }) => adminListPermissions(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListPermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListPermissions>>>
export type AdminListPermissionsQueryError = ErrorType<HTTPValidationError>


export function useAdminListPermissions<TData = Awaited<ReturnType<typeof adminListPermissions>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListPermissionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPermissions>>,
          TError,
          Awaited<ReturnType<typeof adminListPermissions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPermissions<TData = Awaited<ReturnType<typeof adminListPermissions>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPermissions>>,
          TError,
          Awaited<ReturnType<typeof adminListPermissions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPermissions<TData = Awaited<ReturnType<typeof adminListPermissions>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPermissions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Permissions
 */

export function useAdminListPermissions<TData = Awaited<ReturnType<typeof adminListPermissions>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPermissions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListPermissionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






