/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ActivityLogDetailAfterState } from './activityLogDetailAfterState';
import type { ActivityLogDetailBeforeState } from './activityLogDetailBeforeState';
import type { ActivityLogDetailExtra } from './activityLogDetailExtra';
import type { ActorOut } from './actorOut';

/**
 * Single-entry detail — adds full before/after (already redacted) + extra (FR-017).
 */
export interface ActivityLogDetail {
  id: number;
  created_at: string;
  actor: ActorOut;
  action: string;
  entity_type?: string | null;
  record_id?: string | null;
  ip?: string | null;
  changed_fields?: string[] | null;
  before_state?: ActivityLogDetailBeforeState;
  after_state?: ActivityLogDetailAfterState;
  extra?: ActivityLogDetailExtra;
}
