/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ActivityLogListItem } from './activityLogListItem';

export interface ActivityLogList {
  items: ActivityLogListItem[];
  total: number;
  limit: number;
  offset: number;
}
