/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ActorOut } from './actorOut';

/**
 * Compact list row — summary + changed fields, NO before/after (FR-013).
 */
export interface ActivityLogListItem {
  id: number;
  created_at: string;
  actor: ActorOut;
  action: string;
  entity_type?: string | null;
  record_id?: string | null;
  ip?: string | null;
  changed_fields?: string[] | null;
}
