/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AdjCreateDirection } from './adjCreateDirection';
import type { AdjCreateKind } from './adjCreateKind';
import type { AdjCreateReason } from './adjCreateReason';

export interface AdjCreate {
  /**
     * @minLength 1
     * @maxLength 50
     */
  store_code: string;
  kind: AdjCreateKind;
  /**
     * @minLength 1
     * @maxLength 50
     */
  material_code: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  batch_no: string;
  direction: AdjCreateDirection;
  quantity: number | string;
  reason: AdjCreateReason;
  /** @minLength 1 */
  notes: string;
}
