/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdjCreateKind = typeof AdjCreateKind[keyof typeof AdjCreateKind];


export const AdjCreateKind = {
  rm: 'rm',
  fg: 'fg',
} as const;
