/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdjCreateDirection = typeof AdjCreateDirection[keyof typeof AdjCreateDirection];


export const AdjCreateDirection = {
  increase: 'increase',
  decrease: 'decrease',
} as const;
