/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdjCreateReason = typeof AdjCreateReason[keyof typeof AdjCreateReason];


export const AdjCreateReason = {
  damage: 'damage',
  loss: 'loss',
  gain: 'gain',
  expiry_write_off: 'expiry_write_off',
  audit_correction: 'audit_correction',
} as const;
