/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { MaterialRef } from './materialRef';
import type { StoreRef } from './storeRef';

export interface AdjDetail {
  id: number;
  adj_no: string;
  status: string;
  store: StoreRef | null;
  kind: string;
  material: MaterialRef | null;
  batch_no: string;
  direction: string;
  quantity: string;
  delta_quantity: string;
  reason: string;
  notes: string;
  before_quantity: string | null;
  after_quantity: string | null;
  requested_at: string | null;
  requested_by: number | null;
  approved_at: string | null;
  approved_by: number | null;
}
