/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AdjListItem } from './adjListItem';

export interface AdjList {
  items: AdjListItem[];
  total: number;
  limit: number;
  offset: number;
}
