/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface AdjListItem {
  id: number;
  adj_no: string;
  store_code: string | null;
  material_name: string | null;
  reason: string;
  delta_quantity: string;
  notes: string;
  status: string;
}
