/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface AdjPreview {
  adj_no: string;
  item: string;
  store_code: string | null;
  before: string;
  movement: string;
  after: string;
  audit_note: string;
}
