/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface AdjUpdate {
  store_code?: string | null;
  kind?: 'rm' | 'fg' | null;
  material_code?: string | null;
  batch_no?: string | null;
  direction?: 'increase' | 'decrease' | null;
  quantity?: number | string | null;
  reason?: 'damage' | 'loss' | 'gain' | 'expiry_write_off' | 'audit_correction' | null;
  notes?: string | null;
}
