/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AdminUserOut } from './adminUserOut';

export interface AdminUserCreateOut {
  user: AdminUserOut;
  set_password_token: string;
  set_password_url: string;
  invitation_expires_at: string;
}
