/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminGetBatchLedgerParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
