/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListUsersSort = typeof AdminListUsersSort[keyof typeof AdminListUsersSort];


export const AdminListUsersSort = {
  name: 'name',
  last_login: 'last_login',
  created: 'created',
} as const;
