/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AdminListRolesStatus } from './adminListRolesStatus';

export type AdminListRolesParams = {
/**
 * search role name
 */
q?: string | null;
status?: AdminListRolesStatus;
type?: 'admin' | 'staff' | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
