/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListStockMovementsParams = {
store_id?: number | null;
item_type?: 'product' | 'raw_material' | null;
item_id?: number | null;
direction?: 'in' | 'out' | null;
kind?: 'purchase' | 'sale' | 'production' | 'transfer' | 'adjustment' | 'return' | null;
search?: string | null;
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
