/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface AdminResendOut {
  set_password_token: string;
  set_password_url: string;
  invitation_expires_at: string;
}
