/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AdminListUsersOrder } from './adminListUsersOrder';
import type { AdminListUsersSort } from './adminListUsersSort';
import type { AdminListUsersStatus } from './adminListUsersStatus';

export type AdminListUsersParams = {
/**
 * search across first/last/email
 */
q?: string | null;
status?: AdminListUsersStatus;
role?: 'admin' | 'staff' | 'user' | null;
sort?: AdminListUsersSort;
order?: AdminListUsersOrder;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
