/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminUserCreateRole = typeof AdminUserCreateRole[keyof typeof AdminUserCreateRole];


export const AdminUserCreateRole = {
  admin: 'admin',
  staff: 'staff',
  user: 'user',
} as const;
