/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListRolesStatus = typeof AdminListRolesStatus[keyof typeof AdminListRolesStatus];


export const AdminListRolesStatus = {
  active: 'active',
  inactive: 'inactive',
  all: 'all',
} as const;
