/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListStockStrategy = typeof AdminListStockStrategy[keyof typeof AdminListStockStrategy];


export const AdminListStockStrategy = {
  fefo: 'fefo',
  fifo: 'fifo',
} as const;
