/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListStockParams = {
store_id?: number | null;
item_type?: 'product' | 'raw_material' | null;
search?: string | null;
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
