/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListUsersOrder = typeof AdminListUsersOrder[keyof typeof AdminListUsersOrder];


export const AdminListUsersOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
