/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface AdminUserCreate {
  /**
     * @minLength 3
     * @maxLength 320
     */
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  phone?: string | null;
  role?: string;
}
