/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListStockMovementsParams = {
search?: string | null;
store_id?: number | null;
item_type?: 'product' | 'raw_material' | null;
direction?: 'in' | 'out' | null;
kind?: 'grn_receipt' | 'dispatch' | 'transfer' | 'adjustment' | 'return' | 'hold' | 'release' | 'processing_consume' | 'processing_output' | 'manufacturing' | 'manufacturing_consume' | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
