/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListGrnsParams = {
status?: string | null;
supplier_id?: number | null;
store_id?: number | null;
date_from?: string | null;
date_to?: string | null;
search?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
