/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AdminListStockStrategy } from './adminListStockStrategy';

export type AdminListStockParams = {
store_id?: number | null;
material_type?: 'rm' | 'fg' | null;
strategy?: AdminListStockStrategy;
search?: string | null;
batch_no?: string | null;
status?: 'available' | 'reserved' | 'blocked' | 'expired' | 'scrapped' | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
