/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListUsersStatus = typeof AdminListUsersStatus[keyof typeof AdminListUsersStatus];


export const AdminListUsersStatus = {
  active: 'active',
  inactive: 'inactive',
  all: 'all',
} as const;
