/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AdminUserOut } from './adminUserOut';

export interface AdminUserList {
  items: AdminUserOut[];
  total: number;
  limit: number;
  offset: number;
}
