/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListStockBalanceParams = {
search?: string | null;
store_uuid?: string | null;
item_type?: 'product' | 'raw_material' | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
