/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

/**
 * Per-user payload for the admin management surface.

``password_set`` and ``can_resend_set_password_link`` are derived (not
stored): the resend action is offered iff the password is still unset and
the account is live.
 */
export interface AdminUserOut {
  id: number;
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  phone?: string | null;
  role: string;
  is_active: boolean;
  last_login_at?: string | null;
  password_set: boolean;
  can_resend_set_password_link: boolean;
  created_at: string;
}
