/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListLeadsParams = {
q?: string | null;
stage?: string | null;
source_uuid?: string | null;
assignee_uuid?: string | null;
city?: string | null;
state?: string | null;
outcome?: string | null;
closure_reason_uuid?: string | null;
include_deleted?: boolean;
sort?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
