/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListMediaParams = {
/**
 * @minLength 1
 * @maxLength 40
 */
owner_type: string;
/**
 * @minimum 1
 */
owner_id: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
sort?: string;
};
