/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListDoctorAliasesParams = {
search?: string | null;
is_active?: boolean | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
/**
 * @maxLength 40
 */
sort?: string;
};
