/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListStockTransfersParams = {
status?: string | null;
from_store_uuid?: string | null;
to_store_uuid?: string | null;
date_from?: string | null;
date_to?: string | null;
search?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
