/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type AdminListDueRemindersParams = {
due?: boolean;
overdue_only?: boolean;
owner?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
