/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface AssigneeOut {
  uuid: string;
  email: string;
  first_name?: string | null;
  last_name?: string | null;
}
