/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AuditLogListItemAfterState } from './auditLogListItemAfterState';
import type { AuditLogListItemBeforeState } from './auditLogListItemBeforeState';

/**
 * One row in the admin Activity Log table.
 */
export interface AuditLogListItem {
  id: number;
  created_at: string;
  actor_user_id?: number | null;
  actor_email?: string | null;
  actor_role?: string | null;
  action: string;
  target_entity_type?: string | null;
  target_entity_id?: string | null;
  ip?: string | null;
  before_state?: AuditLogListItemBeforeState;
  after_state?: AuditLogListItemAfterState;
}
