/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AuditLogListItem } from './auditLogListItem';

/**
 * Envelope for the admin Activity Log list.
 */
export interface AuditLogListResponse {
  results: AuditLogListItem[];
  count: number;
}
