/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface BatchLabel {
  batch_no: string;
  material_name: string;
  material_code: string;
  manufacture_date: string | null;
  expiry_date: string | null;
  quantity: string;
  uom: string;
}
