/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { BatchStoreRef } from './batchStoreRef';
import type { ExpiryCard } from './expiryCard';
import type { FgFields } from './fgFields';
import type { InboundSummary } from './inboundSummary';
import type { ManufacturingCard } from './manufacturingCard';
import type { OutboundSummary } from './outboundSummary';
import type { RmFields } from './rmFields';

export interface BatchDetail {
  batch_uuid: string;
  batch_no: string;
  material_name: string;
  material_code: string;
  kind: string;
  status: string;
  store: BatchStoreRef;
  current_quantity: string;
  uom: string;
  manufacturing: ManufacturingCard;
  expiry: ExpiryCard;
  inbound: InboundSummary;
  outbound: OutboundSummary;
  running_balance: string;
  movement_count: number;
  rm_fields: RmFields | null;
  fg_fields: FgFields | null;
}
