/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface BatchCreate {
  /**
     * @minLength 1
     * @maxLength 100
     */
  batch_no: string;
  material_code: string;
  store_code: string;
  manufacture_date?: string | null;
  expiry_date?: string | null;
  supplier_code?: string | null;
  grn_no?: string | null;
  harvest_date?: string | null;
  receipt_date?: string | null;
  quality_status?: string | null;
  qc_report_ref?: string | null;
  storage_condition?: string | null;
  bom_version?: string | null;
  produced_qty?: number | string | null;
  pack_size?: string | null;
  label_version?: string | null;
  market_status?: string | null;
}
