/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface BomLineItem {
  id: number;
  raw_material_id?: number | null;
  raw_material_name?: string | null;
  quantity: number;
  unit?: string | null;
}
