/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { BomLineItem } from './bomLineItem';

export interface BomListItem {
  id: number;
  code: string;
  name: string;
  product_id?: number | null;
  product_name?: string | null;
  output_qty?: number | null;
  is_active: boolean;
  created_at: string;
  line_count: number;
  lines: BomLineItem[];
}
