/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { BomListItem } from './bomListItem';

export interface BomListResponse {
  results: BomListItem[];
  count: number;
}
