/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ChangePasswordRequest {
  /** @minLength 1 */
  current_password: string;
  /** @minLength 10 */
  new_password: string;
}
