/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ClosureReasonOutOutcome } from './closureReasonOutOutcome';

export interface ClosureReasonOut {
  uuid: string;
  name: string;
  outcome: ClosureReasonOutOutcome;
  is_active: boolean;
}
