/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ClosureReasonCreateOutcome } from './closureReasonCreateOutcome';

export interface ClosureReasonCreate {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name: string;
  outcome: ClosureReasonCreateOutcome;
}
