/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type ClosureReasonCreateOutcome = typeof ClosureReasonCreateOutcome[keyof typeof ClosureReasonCreateOutcome];


export const ClosureReasonCreateOutcome = {
  WON: 'WON',
  LOST: 'LOST',
} as const;
