/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type ClosureReasonOutOutcome = typeof ClosureReasonOutOutcome[keyof typeof ClosureReasonOutOutcome];


export const ClosureReasonOutOutcome = {
  WON: 'WON',
  LOST: 'LOST',
} as const;
