/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { CourierPartnerListItem } from './courierPartnerListItem';

export interface CourierPartnerListResponse {
  results: CourierPartnerListItem[];
  count: number;
}
