/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CourierPartnerListItem {
  id: number;
  name: string;
  code: string;
  contact_phone?: string | null;
  tracking_url?: string | null;
  is_active: boolean;
  media_count?: number;
  created_at: string;
}
