/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CreateRawMaterialRequest {
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  code: string;
  rm_category_id?: number | null;
  unit?: string | null;
}
