/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type CreateMovementRequestDirection = typeof CreateMovementRequestDirection[keyof typeof CreateMovementRequestDirection];


export const CreateMovementRequestDirection = {
  in: 'in',
  out: 'out',
} as const;
