/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CreateCourierPartnerRequest {
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  code: string;
  contact_phone?: string | null;
  tracking_url?: string | null;
}
