/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { CreateBomLineRequest } from './createBomLineRequest';

export interface CreateBomRequest {
  /**
     * @minLength 1
     * @maxLength 50
     */
  code: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  product_id?: number | null;
  output_qty?: number | null;
  /** @minItems 1 */
  lines: CreateBomLineRequest[];
}
