/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CreateUploadRequest {
  /**
     * @minLength 1
     * @maxLength 40
     */
  owner_type: string;
  /** @minimum 1 */
  owner_id: number;
  /**
     * @minLength 1
     * @maxLength 255
     */
  file_name: string;
  /**
     * @minLength 1
     * @maxLength 120
     */
  content_type: string;
  /** @minimum 1 */
  size_bytes: number;
}
