/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { CreateTransferRequestItemType } from './createTransferRequestItemType';

export interface CreateTransferRequest {
  from_store_id: number;
  to_store_id: number;
  item_type: CreateTransferRequestItemType;
  item_id: number;
  /** @exclusiveMinimum 0 */
  quantity: number;
  unit?: string | null;
  reference?: string | null;
  note?: string | null;
}
