/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CreateBomLineRequest {
  raw_material_id?: number | null;
  /** @exclusiveMinimum 0 */
  quantity: number;
  unit?: string | null;
}
