/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type CreateMovementRequestKind = typeof CreateMovementRequestKind[keyof typeof CreateMovementRequestKind];


export const CreateMovementRequestKind = {
  purchase: 'purchase',
  sale: 'sale',
  production: 'production',
  adjustment: 'adjustment',
  return: 'return',
} as const;
