/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CreateDoctorAliasRequest {
  doctor_id: number;
  /**
     * @minLength 1
     * @maxLength 200
     */
  alias: string;
}
