/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type CreateMovementRequestItemType = typeof CreateMovementRequestItemType[keyof typeof CreateMovementRequestItemType];


export const CreateMovementRequestItemType = {
  product: 'product',
  raw_material: 'raw_material',
} as const;
