/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type CreateTransferRequestItemType = typeof CreateTransferRequestItemType[keyof typeof CreateTransferRequestItemType];


export const CreateTransferRequestItemType = {
  product: 'product',
  raw_material: 'raw_material',
} as const;
