/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type CreateStoreRequestKind = typeof CreateStoreRequestKind[keyof typeof CreateStoreRequestKind];


export const CreateStoreRequestKind = {
  warehouse: 'warehouse',
  factory: 'factory',
  retail: 'retail',
  store: 'store',
} as const;
