/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { CreateMovementRequestDirection } from './createMovementRequestDirection';
import type { CreateMovementRequestItemType } from './createMovementRequestItemType';
import type { CreateMovementRequestKind } from './createMovementRequestKind';

export interface CreateMovementRequest {
  store_id: number;
  item_type: CreateMovementRequestItemType;
  item_id: number;
  direction: CreateMovementRequestDirection;
  kind: CreateMovementRequestKind;
  /** @exclusiveMinimum 0 */
  quantity: number;
  unit?: string | null;
  reference?: string | null;
  note?: string | null;
  counterparty?: string | null;
}
