/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CreateVendorRequest {
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  code: string;
  gstin?: string | null;
  state_code?: string | null;
  city?: string | null;
}
