/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface CreateProductRequest {
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  code: string;
  hsn?: string | null;
  mrp?: number | null;
  gst_rate?: number | null;
  pack_size?: string | null;
}
