/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { DispatchLineOut } from './dispatchLineOut';
import type { InvoiceOut } from './invoiceOut';

export interface DispatchDetail {
  uuid: string;
  challan_no: string;
  customer_or_doctor: string | null;
  dispatch_date: string | null;
  created_at: string;
  lines: DispatchLineOut[];
  invoice: InvoiceOut | null;
}
