/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface DispatchRequest {
  quantity: number | string;
  document_no?: string | null;
  remarks?: string | null;
}
