/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { DispatchLineIn } from './dispatchLineIn';

export interface DispatchCreate {
  customer_or_doctor?: string | null;
  dispatch_date?: string | null;
  generate_invoice?: boolean;
  /** @minItems 1 */
  lines: DispatchLineIn[];
}
