/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface DispatchLineOut {
  batch_uuid: string;
  batch_no: string;
  material_name: string;
  material_code: string;
  store_code: string;
  quantity: string;
  uom: string;
  remarks: string | null;
}
