/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface DispatchListItem {
  uuid: string;
  challan_no: string;
  customer_or_doctor: string | null;
  dispatch_date: string | null;
  line_count: number;
  total_quantity: string;
  invoice_no: string | null;
  payment_status: string | null;
  created_at: string;
}
