/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface DoctorAliasListItem {
  id: number;
  doctor_id: number;
  doctor_name: string;
  alias: string;
  created_at: string;
}
