/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { DoctorAliasListItem } from './doctorAliasListItem';

export interface DoctorAliasListResponse {
  results: DoctorAliasListItem[];
  count: number;
}
