/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { DoctorListItem } from './doctorListItem';

export interface DoctorListResponse {
  results: DoctorListItem[];
  count: number;
}
