/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface DoctorPricingListItem {
  id: number;
  doctor_id: number;
  doctor_name: string;
  product_id: number;
  product_name: string;
  price: number;
  valid_from?: string | null;
  valid_to?: string | null;
  created_at: string;
}
