/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface DoctorListItem {
  id: number;
  name: string;
  code: string;
  clinic_name?: string | null;
  phone?: string | null;
  state_code?: string | null;
  city?: string | null;
  is_active: boolean;
  created_at: string;
}
