/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ExpiryCard {
  expiry_date: string | null;
  days_remaining: number | null;
  fefo_rank: number | null;
  expired: boolean;
}
