/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ActionCell } from './actionCell';

/**
 * One feature row of the grid; `cells` is always length 4 in ACTIONS order.
 */
export interface FeatureRow {
  feature: string;
  label: string;
  cells: ActionCell[];
}
