/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface FgFields {
  bom_version: string | null;
  produced_qty: string | null;
  pack_size: string | null;
  label_version: string | null;
  market_status: string | null;
}
