/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

/**
 * Single uniform response shape for FR-018 (no account-existence oracle).
 */
export interface ForgotPasswordAck {
  detail?: string;
}
