/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AppSchemasGrnWarning } from './appSchemasGrnWarning';
import type { GrnLineOut } from './grnLineOut';
import type { StoreRef } from './storeRef';
import type { SupplierRef } from './supplierRef';

export interface GrnDetail {
  uuid: string;
  grn_no: string;
  status: string;
  supplier: SupplierRef | null;
  store: StoreRef | null;
  vendor_invoice_no: string | null;
  vendor_invoice_date: string | null;
  received_date: string | null;
  notes: string | null;
  grand_total: string;
  lines: GrnLineOut[];
  posted_at: string | null;
  posted_by: string | null;
  created_at: string;
  warnings?: AppSchemasGrnWarning[];
}
