/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface GrnLineIn {
  /**
     * @minLength 1
     * @maxLength 50
     */
  material_code: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  batch_no: string;
  vendor_batch?: string | null;
  quantity: number | string;
  rate: number | string;
  expiry_date?: string | null;
}
