/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { GrnListItem } from './grnListItem';

export interface GrnList {
  items: GrnListItem[];
  total: number;
  limit: number;
  offset: number;
}
