/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AppSchemasGrnWarning } from './appSchemasGrnWarning';
import type { GrnPreviewRow } from './grnPreviewRow';

export interface GrnPreview {
  grn_no: string;
  rows: GrnPreviewRow[];
  ledger_note: string;
  grand_total: string;
  warnings?: AppSchemasGrnWarning[];
}
