/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface GrnPreviewRow {
  line_no: number;
  material_name: string;
  store_code: string | null;
  before: string;
  movement: string;
  after: string;
}
