/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { GrnLineIn } from './grnLineIn';

export interface GrnUpdate {
  supplier_code?: string | null;
  store_code?: string | null;
  vendor_invoice_no?: string | null;
  vendor_invoice_date?: string | null;
  received_date?: string | null;
  notes?: string | null;
  lines?: GrnLineIn[] | null;
}
