/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface InviteUserResponse {
  id: number;
  email: string;
  role: string;
  invitation_expires_at: string;
}
