/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { InviteUserRequestRole } from './inviteUserRequestRole';

export interface InviteUserRequest {
  /**
     * @minLength 3
     * @maxLength 320
     */
  email: string;
  role?: InviteUserRequestRole;
}
