/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type InviteUserRequestRole = typeof InviteUserRequestRole[keyof typeof InviteUserRequestRole];


export const InviteUserRequestRole = {
  admin: 'admin',
  staff: 'staff',
  user: 'user',
} as const;
