/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type InviteUserResponseRole = typeof InviteUserResponseRole[keyof typeof InviteUserResponseRole];


export const InviteUserResponseRole = {
  admin: 'admin',
  staff: 'staff',
  user: 'user',
} as const;
