/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface InviteUserRequest {
  /**
     * @minLength 3
     * @maxLength 320
     */
  email: string;
  role?: string;
}
