/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { InviteUserResponseRole } from './inviteUserResponseRole';

export interface InviteUserResponse {
  id: number;
  email: string;
  role: InviteUserResponseRole;
  invitation_expires_at: string;
}
