/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { InvoiceListItem } from './invoiceListItem';

export interface InvoiceList {
  items: InvoiceListItem[];
  total: number;
  limit: number;
  offset: number;
}
