/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface InvoiceListItem {
  uuid: string;
  invoice_no: string;
  payment_status: string;
  challan_no: string | null;
  customer_or_doctor: string | null;
  created_at: string;
}
