/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AssigneeOut } from './assigneeOut';
import type { ClosureReasonOut } from './closureReasonOut';
import type { LeadDetailStage } from './leadDetailStage';
import type { LeadListItem } from './leadListItem';
import type { NoteOut } from './noteOut';
import type { ReminderOut } from './reminderOut';
import type { SourceOut } from './sourceOut';

export interface LeadDetail {
  uuid: string;
  contact_name: string;
  clinic_name: string;
  phone: string;
  whatsapp_phone: string | null;
  email: string | null;
  estimated_annual_value: string | null;
  city: string | null;
  state: string | null;
  address: string | null;
  stage: LeadDetailStage;
  source: SourceOut | null;
  assignee: AssigneeOut | null;
  messaging_opt_in: boolean;
  closure_reason: ClosureReasonOut | null;
  closure_comment: string | null;
  closed_at: string | null;
  created_at: string;
  updated_at: string;
  notes?: NoteOut[];
  reminders?: ReminderOut[];
  possible_duplicates?: LeadListItem[];
}
