/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type LeadListItemStage = typeof LeadListItemStage[keyof typeof LeadListItemStage];


export const LeadListItemStage = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  FOLLOW_UP: 'FOLLOW_UP',
  WON: 'WON',
  LOST: 'LOST',
} as const;
