/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface LeadCreate {
  /**
     * @minLength 1
     * @maxLength 200
     */
  contact_name: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  clinic_name: string;
  /**
     * @minLength 1
     * @maxLength 20
     */
  phone: string;
  source_uuid: string;
  whatsapp_phone?: string | null;
  email?: string | null;
  estimated_annual_value?: number | string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  assignee_uuid?: string | null;
  messaging_opt_in?: boolean;
}
