/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AssigneeOut } from './assigneeOut';
import type { LeadListItemStage } from './leadListItemStage';
import type { SourceOut } from './sourceOut';

export interface LeadListItem {
  uuid: string;
  contact_name: string;
  clinic_name: string;
  phone: string;
  stage: LeadListItemStage;
  source: SourceOut | null;
  assignee: AssigneeOut | null;
  estimated_annual_value: string | null;
  city: string | null;
  state: string | null;
  created_at: string;
  updated_at: string;
}
