/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type LeadDetailStage = typeof LeadDetailStage[keyof typeof LeadDetailStage];


export const LeadDetailStage = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  FOLLOW_UP: 'FOLLOW_UP',
  WON: 'WON',
  LOST: 'LOST',
} as const;
