/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface LeadUpdate {
  contact_name?: string | null;
  clinic_name?: string | null;
  phone?: string | null;
  source_uuid?: string | null;
  whatsapp_phone?: string | null;
  email?: string | null;
  estimated_annual_value?: number | string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  assignee_uuid?: string | null;
  messaging_opt_in?: boolean | null;
}
