/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { UserRef } from './userRef';

export interface LedgerEntryOut {
  id: number;
  occurred_at: string;
  event: string;
  document_type: string | null;
  document_no: string | null;
  store_code: string;
  qty_in: string;
  qty_out: string;
  running_balance: string;
  user: UserRef | null;
  remarks: string | null;
}
