/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { LedgerEntryOut } from './ledgerEntryOut';

export interface LedgerList {
  items: LedgerEntryOut[];
  total: number;
  limit: number;
  offset: number;
}
