/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

/**
 * Minimal user shape returned in the body of /auth/login and /auth/refresh.
 */
export interface LoginUserOut {
  id: number;
  email: string;
  role: string;
}
