/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ManufacturingLineView {
  raw_material_code: string;
  raw_material_name: string;
  bom_quantity: string;
  unit: string | null;
  required_qty: string;
}
