/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ManufacturingCreate {
  /**
     * @minLength 1
     * @maxLength 50
     */
  product_code: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  bom_code: string;
  planned_output_qty: number | string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  from_store_code: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  to_store_code: string;
  start_date?: string | null;
}
