/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ManufacturingListItem } from './manufacturingListItem';

export interface ManufacturingList {
  items: ManufacturingListItem[];
  total: number;
  limit: number;
  offset: number;
}
