/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ManufacturingListItem {
  id: number;
  mo_no: string;
  status: string;
  product_code: string;
  product_name: string;
  uom: string | null;
  planned_output_qty: string;
  actual_output_qty: string | null;
  yield?: string | null;
  start_date: string | null;
  completed_at: string | null;
  created_at: string;
}
