/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ManufacturingLineView } from './manufacturingLineView';

export interface ManufacturingDetail {
  id: number;
  mo_no: string;
  status: string;
  product_code: string;
  product_name: string;
  uom: string | null;
  bom_code: string;
  bom_version: string | null;
  planned_output_qty: string;
  from_store_code: string;
  to_store_code: string;
  start_date: string | null;
  actual_output_qty: string | null;
  yield?: string | null;
  wastage: string | null;
  output_batch_no: string | null;
  completed_at: string | null;
  lines: ManufacturingLineView[];
  warning?: string | null;
}
