/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ManufacturingUpdate {
  product_code?: string | null;
  bom_code?: string | null;
  planned_output_qty?: number | string | null;
  from_store_code?: string | null;
  to_store_code?: string | null;
  start_date?: string | null;
}
