/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ManufacturingPreviewRow } from './manufacturingPreviewRow';

export interface ManufacturingPreview {
  mo_no: string;
  rows: ManufacturingPreviewRow[];
  warning: string | null;
  note: string;
}
