/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ManufacturingPreviewRow {
  item: string;
  store: string;
  before: string;
  movement: string;
  after: string;
  kind: string;
}
