/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { MaterialOut } from './materialOut';

export interface MaterialList {
  items: MaterialOut[];
  total: number;
}
