/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type MaterialCreateMaterialType = typeof MaterialCreateMaterialType[keyof typeof MaterialCreateMaterialType];


export const MaterialCreateMaterialType = {
  rm: 'rm',
  fg: 'fg',
} as const;
