/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { MaterialCreateMaterialType } from './materialCreateMaterialType';
import type { MaterialCreateUom } from './materialCreateUom';

export interface MaterialCreate {
  /**
     * @minLength 1
     * @maxLength 50
     */
  material_code: string;
  /**
     * @minLength 1
     * @maxLength 255
     */
  material_name: string;
  material_type: MaterialCreateMaterialType;
  uom: MaterialCreateUom;
}
