/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface MaterialUpdate {
  material_code?: string | null;
  material_name?: string | null;
  material_type?: 'rm' | 'fg' | null;
  uom?: 'KG' | 'Jar' | 'Bottle' | 'Piece' | null;
}
