/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type MaterialCreateUom = typeof MaterialCreateUom[keyof typeof MaterialCreateUom];


export const MaterialCreateUom = {
  KG: 'KG',
  Jar: 'Jar',
  Bottle: 'Bottle',
  Piece: 'Piece',
} as const;
