/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface MediaItem {
  uuid: string;
  file_name: string;
  content_type: string;
  size_bytes: number;
  status: string;
  uploaded_by_name?: string | null;
  created_at: string;
}
