/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type MovementListItemDirection = typeof MovementListItemDirection[keyof typeof MovementListItemDirection];


export const MovementListItemDirection = {
  in: 'in',
  out: 'out',
} as const;
