/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { MovementListItemDirection } from './movementListItemDirection';
import type { MovementListItemItemType } from './movementListItemItemType';
import type { MovementListItemKind } from './movementListItemKind';

export interface MovementListItem {
  id: number;
  store_id: number;
  store_name: string;
  item_type: MovementListItemItemType;
  item_id: number;
  item_name: string;
  item_code: string;
  direction: MovementListItemDirection;
  kind: MovementListItemKind;
  quantity: number;
  unit?: string | null;
  reference?: string | null;
  note?: string | null;
  counterparty?: string | null;
  related_store_id?: number | null;
  related_store_name?: string | null;
  created_by_email?: string | null;
  created_at: string;
}
