/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { MovementListItemDirection } from './movementListItemDirection';
import type { MovementListItemItemType } from './movementListItemItemType';
import type { MovementListItemKind } from './movementListItemKind';

export interface MovementListItem {
  id: number;
  direction: MovementListItemDirection;
  kind: MovementListItemKind;
  quantity: number;
  unit: string;
  item_type: MovementListItemItemType;
  item_id: number | null;
  item_name: string;
  item_code: string;
  store_id: number | null;
  store_name: string;
  related_store_name: string | null;
  counterparty: string | null;
  reference: string | null;
  note: string | null;
  created_at: string;
  created_by_email: string | null;
}
