/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type MovementListItemKind = typeof MovementListItemKind[keyof typeof MovementListItemKind];


export const MovementListItemKind = {
  grn_receipt: 'grn_receipt',
  dispatch: 'dispatch',
  transfer: 'transfer',
  adjustment: 'adjustment',
  return: 'return',
  hold: 'hold',
  release: 'release',
  processing_consume: 'processing_consume',
  processing_output: 'processing_output',
  manufacturing: 'manufacturing',
  manufacturing_consume: 'manufacturing_consume',
} as const;
