/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AssigneeOut } from './assigneeOut';

export interface NoteOut {
  uuid: string;
  body: string;
  interaction_type: 'CALL' | 'MEETING' | 'WHATSAPP' | 'EMAIL' | 'OTHER' | null;
  author: AssigneeOut | null;
  created_at: string;
  updated_at: string;
}
