/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface NoteCreate {
  /** @minLength 1 */
  body: string;
  interaction_type?: 'CALL' | 'MEETING' | 'WHATSAPP' | 'EMAIL' | 'OTHER' | null;
}
