/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface NoteUpdate {
  body?: string | null;
  interaction_type?: 'CALL' | 'MEETING' | 'WHATSAPP' | 'EMAIL' | 'OTHER' | null;
}
