/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PaymentStatusUpdatePaymentStatus = typeof PaymentStatusUpdatePaymentStatus[keyof typeof PaymentStatusUpdatePaymentStatus];


export const PaymentStatusUpdatePaymentStatus = {
  unpaid: 'unpaid',
  partial: 'partial',
  paid: 'paid',
} as const;
