/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { PaymentStatusUpdatePaymentStatus } from './paymentStatusUpdatePaymentStatus';

export interface PaymentStatusUpdate {
  payment_status: PaymentStatusUpdatePaymentStatus;
}
