/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface PermissionOut {
  id: number;
  name: string;
  feature: string;
  action: string;
  category: string;
  description: string;
  created_at: string;
  updated_at: string;
}
