/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { PermissionOut } from './permissionOut';

export interface PermissionList {
  items: PermissionOut[];
  total: number;
}
