/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

/**
 * Grant/revoke body — a non-empty list of permission names (or numeric ids).
 */
export interface PermissionRefs {
  /** @minItems 1 */
  permissions: (string | number)[];
}
