/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { SummaryReason } from './summaryReason';
import type { SummarySource } from './summarySource';
import type { SummaryStage } from './summaryStage';

export interface PipelineSummary {
  stages: SummaryStage[];
  by_reason: SummaryReason[];
  by_source: SummarySource[];
}
