/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { PresignedUploadResponseFields } from './presignedUploadResponseFields';

export interface PresignedUploadResponse {
  media_uuid: string;
  upload_url: string;
  fields: PresignedUploadResponseFields;
  expires_in: number;
}
