/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ProcessingUpdate {
  input_material_code?: string | null;
  from_store_code?: string | null;
  input_batch_no?: string | null;
  quantity_to_consume?: number | string | null;
  output_material_code?: string | null;
  to_store_code?: string | null;
  notes?: string | null;
}
