/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ProcessingCreate {
  /**
     * @minLength 1
     * @maxLength 50
     */
  input_material_code: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  from_store_code: string;
  input_batch_no?: string | null;
  quantity_to_consume: number | string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  output_material_code: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  to_store_code: string;
  notes?: string | null;
}
