/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ProcessingOutput {
  material_id: number;
  material_code: string;
  material_name: string;
  to_store_id: string;
  to_store_name: string;
  notes: string | null;
}
