/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ProcessingResult {
  output_quantity: string | null;
  conversion_ratio: string | null;
  yield?: string | null;
  wastage: string | null;
  output_batch_id: string | null;
  output_batch_no: string | null;
  completed_at: string | null;
  completed_by: string | null;
}
