/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ProcessingPreviewRow {
  item_name: string;
  store_code: string;
  before: string;
  movement: string;
  after: string;
}
