/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ProcessingInput } from './processingInput';
import type { ProcessingOutput } from './processingOutput';
import type { ProcessingResult } from './processingResult';

export interface ProcessingDetail {
  id: number;
  pr_no: string;
  status: string;
  input: ProcessingInput;
  output: ProcessingOutput;
  result: ProcessingResult;
  warning?: string | null;
}
