/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ProcessingListItem } from './processingListItem';

export interface ProcessingList {
  items: ProcessingListItem[];
  total: number;
  limit: number;
  offset: number;
}
