/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ProcessingListItem {
  uuid: string;
  pr_no: string;
  status: string;
  input_material_name: string;
  input_material_code: string;
  from_store_name: string;
  quantity_to_consume: string;
  output_material_name: string;
  output_quantity: string | null;
  conversion_ratio: string | null;
  completed_at: string | null;
  created_at: string;
}
