/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { RawMaterialListItem } from './rawMaterialListItem';

export interface RawMaterialListResponse {
  results: RawMaterialListItem[];
  count: number;
}
