/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface RawMaterialListItem {
  id: number;
  name: string;
  code: string;
  rm_category_id?: number | null;
  rm_category_name?: string | null;
  unit?: string | null;
  is_active: boolean;
  created_at: string;
}
