/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { LoginUserOut } from './loginUserOut';

/**
 * Same body shape as login; explicit alias for clarity at the endpoint.
 */
export interface RefreshResponse {
  user: LoginUserOut;
}
