/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ReminderCreate {
  due_date: string;
  due_time?: string | null;
  note?: string | null;
  owner_uuid?: string | null;
}
