/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ReminderWithLead } from './reminderWithLead';

export interface ReminderList {
  items: ReminderWithLead[];
  total: number;
  limit: number;
  offset: number;
}
