/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type ReminderWithLeadStatus = typeof ReminderWithLeadStatus[keyof typeof ReminderWithLeadStatus];


export const ReminderWithLeadStatus = {
  PENDING: 'PENDING',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
} as const;
