/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type ReminderOutStatus = typeof ReminderOutStatus[keyof typeof ReminderOutStatus];


export const ReminderOutStatus = {
  PENDING: 'PENDING',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
} as const;
