/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ReminderUpdate {
  due_date?: string | null;
  due_time?: string | null;
  note?: string | null;
  owner_uuid?: string | null;
}
