/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AssigneeOut } from './assigneeOut';
import type { ReminderLeadRef } from './reminderLeadRef';
import type { ReminderWithLeadStatus } from './reminderWithLeadStatus';

export interface ReminderWithLead {
  uuid: string;
  due_date: string;
  due_time: string | null;
  note: string | null;
  owner: AssigneeOut | null;
  status: ReminderWithLeadStatus;
  completed_at: string | null;
  client_message_status: 'PENDING' | 'SENT' | 'SKIPPED_NO_CONSENT' | 'FAILED' | 'NA' | null;
  client_message_sent_at: string | null;
  created_at: string;
  warning?: string | null;
  lead: ReminderLeadRef;
  is_overdue?: boolean;
}
