/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ReminderLeadRefStage } from './reminderLeadRefStage';

export interface ReminderLeadRef {
  uuid: string;
  contact_name: string;
  clinic_name: string;
  stage: ReminderLeadRefStage;
}
