/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type ReminderLeadRefStage = typeof ReminderLeadRefStage[keyof typeof ReminderLeadRefStage];


export const ReminderLeadRefStage = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  FOLLOW_UP: 'FOLLOW_UP',
  WON: 'WON',
  LOST: 'LOST',
} as const;
