/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface ResetPasswordRequest {
  /** @minLength 1 */
  reset_token: string;
  /** @minLength 10 */
  new_password: string;
}
