/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface RmCategoryListItem {
  id: number;
  name: string;
  code: string;
  description?: string | null;
  is_active: boolean;
  created_at: string;
}
