/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface RmFields {
  supplier: string | null;
  grn_no: string | null;
  harvest_date: string | null;
  receipt_date: string | null;
  quality_status: string | null;
  qc_report_ref: string | null;
  storage_condition: string | null;
}
