/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type RoleStatusUpdateStatus = typeof RoleStatusUpdateStatus[keyof typeof RoleStatusUpdateStatus];


export const RoleStatusUpdateStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
