/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type RoleCreateType = typeof RoleCreateType[keyof typeof RoleCreateType];


export const RoleCreateType = {
  admin: 'admin',
  staff: 'staff',
} as const;
