/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { RoleStatusUpdateStatus } from './roleStatusUpdateStatus';

export interface RoleStatusUpdate {
  status: RoleStatusUpdateStatus;
}
