/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface RoleUpdate {
  name?: string | null;
  type?: 'admin' | 'staff' | null;
  description?: string | null;
}
