/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { PermissionItem } from './permissionItem';
import type { RoleListItem } from './roleListItem';

export interface RoleListResponse {
  results: RoleListItem[];
  all_permissions: PermissionItem[];
  total_permissions: number;
  count: number;
}
