/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { RoleOut } from './roleOut';

export interface RoleList {
  items: RoleOut[];
  total: number;
  limit: number;
  offset: number;
}
