/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type StageChangeStage = typeof StageChangeStage[keyof typeof StageChangeStage];


export const StageChangeStage = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  FOLLOW_UP: 'FOLLOW_UP',
  WON: 'WON',
  LOST: 'LOST',
} as const;
