/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StageChangeStage } from './stageChangeStage';

export interface StageChange {
  stage: StageChangeStage;
  closure_reason_uuid?: string | null;
  closure_comment?: string | null;
}
