/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StLineIn } from './stLineIn';

export interface StCreate {
  /**
     * @minLength 1
     * @maxLength 50
     */
  from_store_code: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  to_store_code: string;
  notes?: string | null;
  /** @minItems 1 */
  lines: StLineIn[];
}
