/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AppSchemasStockTransferWarning } from './appSchemasStockTransferWarning';
import type { StLineOut } from './stLineOut';
import type { StoreRef } from './storeRef';

export interface StDetail {
  id: number;
  st_no: string;
  status: string;
  from_store: StoreRef | null;
  to_store: StoreRef | null;
  notes: string | null;
  lines: StLineOut[];
  requested_at: string | null;
  requested_by: number | null;
  approved_at: string | null;
  approved_by: number | null;
  dispatched_at: string | null;
  dispatched_by: number | null;
  received_at: string | null;
  received_by: number | null;
  cancelled_at: string | null;
  cancelled_by: number | null;
  warnings?: AppSchemasStockTransferWarning[];
}
