/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StListItem } from './stListItem';

export interface StList {
  items: StListItem[];
  total: number;
  limit: number;
  offset: number;
}
