/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StLineInKind } from './stLineInKind';

export interface StLineIn {
  kind: StLineInKind;
  /**
     * @minLength 1
     * @maxLength 50
     */
  material_code: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  source_batch_no: string;
  quantity: number | string;
}
