/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface StLineOut {
  uuid: string;
  line_no: number;
  kind: string;
  material_code: string;
  material_name: string;
  source_batch_no: string;
  quantity: string;
  dest_batch_no: string | null;
}
