/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StockBalanceItemItemType } from './stockBalanceItemItemType';

export interface StockBalanceItem {
  store_id: number;
  store_name: string;
  item_type: StockBalanceItemItemType;
  item_id: number;
  item_name: string;
  item_code: string;
  unit?: string | null;
  quantity: number;
}
