/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StockBalanceItemItemType } from './stockBalanceItemItemType';

export interface StockBalanceItem {
  item_id: number;
  item_type: StockBalanceItemItemType;
  store_uuid: string;
  quantity: number;
  item_name: string;
  item_code: string;
  store_name: string;
  unit: string;
}
