/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StockListItem } from './stockListItem';

export interface StockList {
  items: StockListItem[];
  total: number;
  limit: number;
  offset: number;
}
