/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type StockBalanceItemItemType = typeof StockBalanceItemItemType[keyof typeof StockBalanceItemItemType];


export const StockBalanceItemItemType = {
  product: 'product',
  raw_material: 'raw_material',
} as const;
