/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StockBalanceItem } from './stockBalanceItem';

export interface StockBalanceResponse {
  results: StockBalanceItem[];
  count: number;
  limit: number;
  offset: number;
}
