/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { StoreCreateStoreType } from './storeCreateStoreType';

export interface StoreCreate {
  /**
     * @minLength 1
     * @maxLength 50
     */
  store_code: string;
  /**
     * @minLength 1
     * @maxLength 255
     */
  store_name: string;
  store_type: StoreCreateStoreType;
}
