/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface StoreUpdate {
  store_code?: string | null;
  store_name?: string | null;
  store_type?: 'finished_goods' | 'raw_material' | null;
}
