/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

/**
 * One row in the Stores table.
 */
export interface StoreListItem {
  id: number;
  name: string;
  code: string;
  kind: string;
  city?: string | null;
  is_active: boolean;
  created_at: string;
}
