/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface StoreOut {
  uuid: string;
  store_code: string;
  store_name: string;
  store_type: string;
  total_available_units: string;
}
