/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type StoreCreateStoreType = typeof StoreCreateStoreType[keyof typeof StoreCreateStoreType];


export const StoreCreateStoreType = {
  finished_goods: 'finished_goods',
  raw_material: 'raw_material',
} as const;
