/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { AppSchemasStockTransferWarning } from './appSchemasStockTransferWarning';
import type { StPreviewRow } from './stPreviewRow';

export interface StPreview {
  st_no: string;
  rows: StPreviewRow[];
  note: string;
  warnings?: AppSchemasStockTransferWarning[];
}
