/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface StPreviewRow {
  line_no: number;
  item: string;
  store_code: string | null;
  before: string;
  movement: string;
  after: string;
}
