/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { SummaryStageStage } from './summaryStageStage';

export interface SummaryStage {
  stage: SummaryStageStage;
  count: number;
  total_estimated_value: string;
}
