/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type SummaryStageStage = typeof SummaryStageStage[keyof typeof SummaryStageStage];


export const SummaryStageStage = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  FOLLOW_UP: 'FOLLOW_UP',
  WON: 'WON',
  LOST: 'LOST',
} as const;
