/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type SummaryReasonOutcome = typeof SummaryReasonOutcome[keyof typeof SummaryReasonOutcome];


export const SummaryReasonOutcome = {
  WON: 'WON',
  LOST: 'LOST',
} as const;
