/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { SummaryReasonOutcome } from './summaryReasonOutcome';

export interface SummaryReason {
  reason: string;
  outcome: SummaryReasonOutcome;
  count: number;
}
