/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { UserRef } from './userRef';

export interface TimelineEventOut {
  id: number;
  event_type: string;
  occurred_at: string;
  reference_document: string | null;
  remarks: string | null;
  user: UserRef | null;
}
