/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface TraceDispatch {
  challan_no: string;
  customer_or_doctor: string | null;
  dispatch_date: string | null;
}
