/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface TraceManufacturing {
  mo_no: string;
  bom_version: string | null;
  production_date: string | null;
  operator: string | null;
}
