/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface TraceFinishedGoods {
  fg_batch_no: string;
  fg_material: string;
  quantity_produced: string | null;
}
