/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { TraceAccounts } from './traceAccounts';
import type { TraceDispatch } from './traceDispatch';
import type { TraceFinishedGoods } from './traceFinishedGoods';
import type { TraceManufacturing } from './traceManufacturing';
import type { TraceRawMaterial } from './traceRawMaterial';

export interface TraceabilityOut {
  raw_material: TraceRawMaterial | null;
  manufacturing: TraceManufacturing | null;
  finished_goods: TraceFinishedGoods | null;
  dispatch: TraceDispatch | null;
  accounts: TraceAccounts | null;
}
