/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

/**
 * Partial update of the signed-in user's own profile (feature 006).

All fields optional. `extra="forbid"` turns an attempt to change a
non-editable attribute (email, role, …) into a 422 instead of a silent
no-op. `str_strip_whitespace` trims input; a trimmed-empty value clears the
field (normalized to None). The handler applies only the fields present in
the payload via `model_dump(exclude_unset=True)`, so omitted fields are
left untouched.
 */
export interface UpdateProfileRequest {
  first_name?: string | null;
  last_name?: string | null;
  phone?: string | null;
}
