/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface UpdateVendorRequest {
  name?: string | null;
  code?: string | null;
  gstin?: string | null;
  state_code?: string | null;
  city?: string | null;
}
