/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface UpdateProductRequest {
  name?: string | null;
  code?: string | null;
  hsn?: string | null;
  mrp?: number | null;
  gst_rate?: number | null;
  pack_size?: string | null;
}
