/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface UpdateRawMaterialRequest {
  name?: string | null;
  code?: string | null;
  rm_category_id?: number | null;
  unit?: string | null;
}
