/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface UpdateDoctorPricingRequest {
  doctor_id?: number | null;
  product_id?: number | null;
  price?: number | null;
  valid_from?: string | null;
  valid_to?: string | null;
}
