/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface UpdateRmCategoryRequest {
  name?: string | null;
  code?: string | null;
  description?: string | null;
}
