/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { UserListItem } from './userListItem';

/**
 * Envelope for the admin Users list.
 */
export interface UserListResponse {
  results: UserListItem[];
  count: number;
}
