/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface VendorListItem {
  id: number;
  name: string;
  code: string;
  gstin?: string | null;
  state_code?: string | null;
  city?: string | null;
  is_active: boolean;
  media_count?: number;
  created_at: string;
}
