/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export interface VerifyOtpRequest {
  /**
     * @minLength 3
     * @maxLength 320
     */
  email: string;
  /**
     * @minLength 6
     * @maxLength 6
     */
  otp: string;
}
